/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.bibbox.medicaldataset.model.impl;

import aQute.bnd.annotation.ProviderType;

import at.graz.meduni.bibbox.medicaldataset.model.ImportMedicalDataSet;
import at.graz.meduni.bibbox.medicaldataset.model.ImportMedicalDataSetModel;
import at.graz.meduni.bibbox.medicaldataset.model.ImportMedicalDataSetSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ImportMedicalDataSet service. Represents a row in the &quot;FOO_ImportMedicalDataSet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ImportMedicalDataSetModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ImportMedicalDataSetImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ImportMedicalDataSetImpl
 * @see ImportMedicalDataSet
 * @see ImportMedicalDataSetModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class ImportMedicalDataSetModelImpl extends BaseModelImpl<ImportMedicalDataSet>
	implements ImportMedicalDataSetModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a import medical data set model instance should use the {@link ImportMedicalDataSet} interface instead.
	 */
	public static final String TABLE_NAME = "FOO_ImportMedicalDataSet";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "importMedicalDataSetId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "status", Types.INTEGER },
			{ "statusByUserId", Types.BIGINT },
			{ "statusByUserName", Types.VARCHAR },
			{ "statusDate", Types.TIMESTAMP },
			{ "importName", Types.VARCHAR },
			{ "importType", Types.VARCHAR },
			{ "imiJobId", Types.BIGINT },
			{ "description", Types.VARCHAR },
			{ "fileName", Types.VARCHAR },
			{ "filePath", Types.VARCHAR },
			{ "importStatus", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("importMedicalDataSetId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("importName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("importType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("imiJobId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fileName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("filePath", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("importStatus", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table FOO_ImportMedicalDataSet (uuid_ VARCHAR(75) null,importMedicalDataSetId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,importName VARCHAR(75) null,importType VARCHAR(75) null,imiJobId LONG,description STRING null,fileName VARCHAR(75) null,filePath VARCHAR(1000) null,importStatus INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table FOO_ImportMedicalDataSet";
	public static final String ORDER_BY_JPQL = " ORDER BY importMedicalDataSet.importMedicalDataSetId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY FOO_ImportMedicalDataSet.importMedicalDataSetId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(at.graz.meduni.bibbox.medicaldataset.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.at.graz.meduni.bibbox.medicaldataset.model.ImportMedicalDataSet"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(at.graz.meduni.bibbox.medicaldataset.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.at.graz.meduni.bibbox.medicaldataset.model.ImportMedicalDataSet"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(at.graz.meduni.bibbox.medicaldataset.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.at.graz.meduni.bibbox.medicaldataset.model.ImportMedicalDataSet"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long GROUPID_COLUMN_BITMASK = 2L;
	public static final long UUID_COLUMN_BITMASK = 4L;
	public static final long IMPORTMEDICALDATASETID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ImportMedicalDataSet toModel(
		ImportMedicalDataSetSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ImportMedicalDataSet model = new ImportMedicalDataSetImpl();

		model.setUuid(soapModel.getUuid());
		model.setImportMedicalDataSetId(soapModel.getImportMedicalDataSetId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setImportName(soapModel.getImportName());
		model.setImportType(soapModel.getImportType());
		model.setImiJobId(soapModel.getImiJobId());
		model.setDescription(soapModel.getDescription());
		model.setFileName(soapModel.getFileName());
		model.setFilePath(soapModel.getFilePath());
		model.setImportStatus(soapModel.getImportStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ImportMedicalDataSet> toModels(
		ImportMedicalDataSetSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ImportMedicalDataSet> models = new ArrayList<ImportMedicalDataSet>(soapModels.length);

		for (ImportMedicalDataSetSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(at.graz.meduni.bibbox.medicaldataset.service.util.ServiceProps.get(
				"lock.expiration.time.at.graz.meduni.bibbox.medicaldataset.model.ImportMedicalDataSet"));

	public ImportMedicalDataSetModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _importMedicalDataSetId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setImportMedicalDataSetId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _importMedicalDataSetId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ImportMedicalDataSet.class;
	}

	@Override
	public String getModelClassName() {
		return ImportMedicalDataSet.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("importMedicalDataSetId", getImportMedicalDataSetId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("status", getStatus());
		attributes.put("statusByUserId", getStatusByUserId());
		attributes.put("statusByUserName", getStatusByUserName());
		attributes.put("statusDate", getStatusDate());
		attributes.put("importName", getImportName());
		attributes.put("importType", getImportType());
		attributes.put("imiJobId", getImiJobId());
		attributes.put("description", getDescription());
		attributes.put("fileName", getFileName());
		attributes.put("filePath", getFilePath());
		attributes.put("importStatus", getImportStatus());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long importMedicalDataSetId = (Long)attributes.get(
				"importMedicalDataSetId");

		if (importMedicalDataSetId != null) {
			setImportMedicalDataSetId(importMedicalDataSetId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		Long statusByUserId = (Long)attributes.get("statusByUserId");

		if (statusByUserId != null) {
			setStatusByUserId(statusByUserId);
		}

		String statusByUserName = (String)attributes.get("statusByUserName");

		if (statusByUserName != null) {
			setStatusByUserName(statusByUserName);
		}

		Date statusDate = (Date)attributes.get("statusDate");

		if (statusDate != null) {
			setStatusDate(statusDate);
		}

		String importName = (String)attributes.get("importName");

		if (importName != null) {
			setImportName(importName);
		}

		String importType = (String)attributes.get("importType");

		if (importType != null) {
			setImportType(importType);
		}

		Long imiJobId = (Long)attributes.get("imiJobId");

		if (imiJobId != null) {
			setImiJobId(imiJobId);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		String fileName = (String)attributes.get("fileName");

		if (fileName != null) {
			setFileName(fileName);
		}

		String filePath = (String)attributes.get("filePath");

		if (filePath != null) {
			setFilePath(filePath);
		}

		Integer importStatus = (Integer)attributes.get("importStatus");

		if (importStatus != null) {
			setImportStatus(importStatus);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getImportMedicalDataSetId() {
		return _importMedicalDataSetId;
	}

	@Override
	public void setImportMedicalDataSetId(long importMedicalDataSetId) {
		_columnBitmask = -1L;

		_importMedicalDataSetId = importMedicalDataSetId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return StringPool.BLANK;
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getImportName() {
		if (_importName == null) {
			return StringPool.BLANK;
		}
		else {
			return _importName;
		}
	}

	@Override
	public void setImportName(String importName) {
		_importName = importName;
	}

	@JSON
	@Override
	public String getImportType() {
		if (_importType == null) {
			return StringPool.BLANK;
		}
		else {
			return _importType;
		}
	}

	@Override
	public void setImportType(String importType) {
		_importType = importType;
	}

	@JSON
	@Override
	public long getImiJobId() {
		return _imiJobId;
	}

	@Override
	public void setImiJobId(long imiJobId) {
		_imiJobId = imiJobId;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public String getFileName() {
		if (_fileName == null) {
			return StringPool.BLANK;
		}
		else {
			return _fileName;
		}
	}

	@Override
	public void setFileName(String fileName) {
		_fileName = fileName;
	}

	@JSON
	@Override
	public String getFilePath() {
		if (_filePath == null) {
			return StringPool.BLANK;
		}
		else {
			return _filePath;
		}
	}

	@Override
	public void setFilePath(String filePath) {
		_filePath = filePath;
	}

	@JSON
	@Override
	public int getImportStatus() {
		return _importStatus;
	}

	@Override
	public void setImportStatus(int importStatus) {
		_importStatus = importStatus;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				ImportMedicalDataSet.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			ImportMedicalDataSet.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ImportMedicalDataSet toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ImportMedicalDataSet)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ImportMedicalDataSetImpl importMedicalDataSetImpl = new ImportMedicalDataSetImpl();

		importMedicalDataSetImpl.setUuid(getUuid());
		importMedicalDataSetImpl.setImportMedicalDataSetId(getImportMedicalDataSetId());
		importMedicalDataSetImpl.setGroupId(getGroupId());
		importMedicalDataSetImpl.setCompanyId(getCompanyId());
		importMedicalDataSetImpl.setUserId(getUserId());
		importMedicalDataSetImpl.setUserName(getUserName());
		importMedicalDataSetImpl.setCreateDate(getCreateDate());
		importMedicalDataSetImpl.setModifiedDate(getModifiedDate());
		importMedicalDataSetImpl.setStatus(getStatus());
		importMedicalDataSetImpl.setStatusByUserId(getStatusByUserId());
		importMedicalDataSetImpl.setStatusByUserName(getStatusByUserName());
		importMedicalDataSetImpl.setStatusDate(getStatusDate());
		importMedicalDataSetImpl.setImportName(getImportName());
		importMedicalDataSetImpl.setImportType(getImportType());
		importMedicalDataSetImpl.setImiJobId(getImiJobId());
		importMedicalDataSetImpl.setDescription(getDescription());
		importMedicalDataSetImpl.setFileName(getFileName());
		importMedicalDataSetImpl.setFilePath(getFilePath());
		importMedicalDataSetImpl.setImportStatus(getImportStatus());

		importMedicalDataSetImpl.resetOriginalValues();

		return importMedicalDataSetImpl;
	}

	@Override
	public int compareTo(ImportMedicalDataSet importMedicalDataSet) {
		int value = 0;

		if (getImportMedicalDataSetId() < importMedicalDataSet.getImportMedicalDataSetId()) {
			value = -1;
		}
		else if (getImportMedicalDataSetId() > importMedicalDataSet.getImportMedicalDataSetId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ImportMedicalDataSet)) {
			return false;
		}

		ImportMedicalDataSet importMedicalDataSet = (ImportMedicalDataSet)obj;

		long primaryKey = importMedicalDataSet.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ImportMedicalDataSetModelImpl importMedicalDataSetModelImpl = this;

		importMedicalDataSetModelImpl._originalUuid = importMedicalDataSetModelImpl._uuid;

		importMedicalDataSetModelImpl._originalGroupId = importMedicalDataSetModelImpl._groupId;

		importMedicalDataSetModelImpl._setOriginalGroupId = false;

		importMedicalDataSetModelImpl._originalCompanyId = importMedicalDataSetModelImpl._companyId;

		importMedicalDataSetModelImpl._setOriginalCompanyId = false;

		importMedicalDataSetModelImpl._setModifiedDate = false;

		importMedicalDataSetModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ImportMedicalDataSet> toCacheModel() {
		ImportMedicalDataSetCacheModel importMedicalDataSetCacheModel = new ImportMedicalDataSetCacheModel();

		importMedicalDataSetCacheModel.uuid = getUuid();

		String uuid = importMedicalDataSetCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			importMedicalDataSetCacheModel.uuid = null;
		}

		importMedicalDataSetCacheModel.importMedicalDataSetId = getImportMedicalDataSetId();

		importMedicalDataSetCacheModel.groupId = getGroupId();

		importMedicalDataSetCacheModel.companyId = getCompanyId();

		importMedicalDataSetCacheModel.userId = getUserId();

		importMedicalDataSetCacheModel.userName = getUserName();

		String userName = importMedicalDataSetCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			importMedicalDataSetCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			importMedicalDataSetCacheModel.createDate = createDate.getTime();
		}
		else {
			importMedicalDataSetCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			importMedicalDataSetCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			importMedicalDataSetCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		importMedicalDataSetCacheModel.status = getStatus();

		importMedicalDataSetCacheModel.statusByUserId = getStatusByUserId();

		importMedicalDataSetCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = importMedicalDataSetCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			importMedicalDataSetCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			importMedicalDataSetCacheModel.statusDate = statusDate.getTime();
		}
		else {
			importMedicalDataSetCacheModel.statusDate = Long.MIN_VALUE;
		}

		importMedicalDataSetCacheModel.importName = getImportName();

		String importName = importMedicalDataSetCacheModel.importName;

		if ((importName != null) && (importName.length() == 0)) {
			importMedicalDataSetCacheModel.importName = null;
		}

		importMedicalDataSetCacheModel.importType = getImportType();

		String importType = importMedicalDataSetCacheModel.importType;

		if ((importType != null) && (importType.length() == 0)) {
			importMedicalDataSetCacheModel.importType = null;
		}

		importMedicalDataSetCacheModel.imiJobId = getImiJobId();

		importMedicalDataSetCacheModel.description = getDescription();

		String description = importMedicalDataSetCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			importMedicalDataSetCacheModel.description = null;
		}

		importMedicalDataSetCacheModel.fileName = getFileName();

		String fileName = importMedicalDataSetCacheModel.fileName;

		if ((fileName != null) && (fileName.length() == 0)) {
			importMedicalDataSetCacheModel.fileName = null;
		}

		importMedicalDataSetCacheModel.filePath = getFilePath();

		String filePath = importMedicalDataSetCacheModel.filePath;

		if ((filePath != null) && (filePath.length() == 0)) {
			importMedicalDataSetCacheModel.filePath = null;
		}

		importMedicalDataSetCacheModel.importStatus = getImportStatus();

		return importMedicalDataSetCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(39);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", importMedicalDataSetId=");
		sb.append(getImportMedicalDataSetId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", statusByUserId=");
		sb.append(getStatusByUserId());
		sb.append(", statusByUserName=");
		sb.append(getStatusByUserName());
		sb.append(", statusDate=");
		sb.append(getStatusDate());
		sb.append(", importName=");
		sb.append(getImportName());
		sb.append(", importType=");
		sb.append(getImportType());
		sb.append(", imiJobId=");
		sb.append(getImiJobId());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", fileName=");
		sb.append(getFileName());
		sb.append(", filePath=");
		sb.append(getFilePath());
		sb.append(", importStatus=");
		sb.append(getImportStatus());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(61);

		sb.append("<model><model-name>");
		sb.append(
			"at.graz.meduni.bibbox.medicaldataset.model.ImportMedicalDataSet");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>importMedicalDataSetId</column-name><column-value><![CDATA[");
		sb.append(getImportMedicalDataSetId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserId</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserName</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusDate</column-name><column-value><![CDATA[");
		sb.append(getStatusDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>importName</column-name><column-value><![CDATA[");
		sb.append(getImportName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>importType</column-name><column-value><![CDATA[");
		sb.append(getImportType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imiJobId</column-name><column-value><![CDATA[");
		sb.append(getImiJobId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fileName</column-name><column-value><![CDATA[");
		sb.append(getFileName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>filePath</column-name><column-value><![CDATA[");
		sb.append(getFilePath());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>importStatus</column-name><column-value><![CDATA[");
		sb.append(getImportStatus());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = ImportMedicalDataSet.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			ImportMedicalDataSet.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _importMedicalDataSetId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _importName;
	private String _importType;
	private long _imiJobId;
	private String _description;
	private String _fileName;
	private String _filePath;
	private int _importStatus;
	private long _columnBitmask;
	private ImportMedicalDataSet _escapedModel;
}