/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.bibbox.medicaldataset.model.impl;

import aQute.bnd.annotation.ProviderType;

import at.graz.meduni.bibbox.medicaldataset.model.KloetzelBuch;
import at.graz.meduni.bibbox.medicaldataset.model.KloetzelBuchModel;
import at.graz.meduni.bibbox.medicaldataset.model.KloetzelBuchSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the KloetzelBuch service. Represents a row in the &quot;FOO_KloetzelBuch&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link KloetzelBuchModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link KloetzelBuchImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see KloetzelBuchImpl
 * @see KloetzelBuch
 * @see KloetzelBuchModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class KloetzelBuchModelImpl extends BaseModelImpl<KloetzelBuch>
	implements KloetzelBuchModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a kloetzel buch model instance should use the {@link KloetzelBuch} interface instead.
	 */
	public static final String TABLE_NAME = "FOO_KloetzelBuch";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "kloetzelBuchId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "status", Types.INTEGER },
			{ "statusByUserId", Types.BIGINT },
			{ "statusByUserName", Types.VARCHAR },
			{ "statusDate", Types.TIMESTAMP },
			{ "medicalRecordId", Types.BIGINT },
			{ "histonumberStart", Types.BIGINT },
			{ "histonumberEnd", Types.BIGINT },
			{ "histonumberRunning", Types.INTEGER },
			{ "histonumber", Types.BIGINT },
			{ "kloetzelBuchRunning", Types.INTEGER },
			{ "oid", Types.VARCHAR },
			{ "bid", Types.VARCHAR },
			{ "area", Types.VARCHAR },
			{ "type_", Types.VARCHAR },
			{ "acronym", Types.VARCHAR },
			{ "text_", Types.VARCHAR },
			{ "info", Types.VARCHAR },
			{ "count", Types.INTEGER },
			{ "numberOfPieces", Types.INTEGER },
			{ "kbStatus", Types.INTEGER },
			{ "sort", Types.INTEGER },
			{ "color", Types.VARCHAR },
			{ "kbDate", Types.TIMESTAMP },
			{ "day", Types.VARCHAR },
			{ "pocessinguser", Types.VARCHAR },
			{ "organizationUnit", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("kloetzelBuchId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("medicalRecordId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("histonumberStart", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("histonumberEnd", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("histonumberRunning", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("histonumber", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("kloetzelBuchRunning", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("oid", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("bid", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("area", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("acronym", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("text_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("info", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("count", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("numberOfPieces", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("kbStatus", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("sort", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("color", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("kbDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("day", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("pocessinguser", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("organizationUnit", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table FOO_KloetzelBuch (uuid_ VARCHAR(75) null,kloetzelBuchId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,medicalRecordId LONG,histonumberStart LONG,histonumberEnd LONG,histonumberRunning INTEGER,histonumber LONG,kloetzelBuchRunning INTEGER,oid VARCHAR(75) null,bid VARCHAR(75) null,area VARCHAR(75) null,type_ VARCHAR(75) null,acronym VARCHAR(75) null,text_ STRING null,info STRING null,count INTEGER,numberOfPieces INTEGER,kbStatus INTEGER,sort INTEGER,color VARCHAR(75) null,kbDate DATE null,day VARCHAR(75) null,pocessinguser VARCHAR(75) null,organizationUnit VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table FOO_KloetzelBuch";
	public static final String ORDER_BY_JPQL = " ORDER BY kloetzelBuch.kloetzelBuchId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY FOO_KloetzelBuch.kloetzelBuchId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(at.graz.meduni.bibbox.medicaldataset.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.at.graz.meduni.bibbox.medicaldataset.model.KloetzelBuch"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(at.graz.meduni.bibbox.medicaldataset.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.at.graz.meduni.bibbox.medicaldataset.model.KloetzelBuch"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(at.graz.meduni.bibbox.medicaldataset.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.at.graz.meduni.bibbox.medicaldataset.model.KloetzelBuch"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long GROUPID_COLUMN_BITMASK = 2L;
	public static final long MEDICALRECORDID_COLUMN_BITMASK = 4L;
	public static final long UUID_COLUMN_BITMASK = 8L;
	public static final long KLOETZELBUCHID_COLUMN_BITMASK = 16L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static KloetzelBuch toModel(KloetzelBuchSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		KloetzelBuch model = new KloetzelBuchImpl();

		model.setUuid(soapModel.getUuid());
		model.setKloetzelBuchId(soapModel.getKloetzelBuchId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setMedicalRecordId(soapModel.getMedicalRecordId());
		model.setHistonumberStart(soapModel.getHistonumberStart());
		model.setHistonumberEnd(soapModel.getHistonumberEnd());
		model.setHistonumberRunning(soapModel.getHistonumberRunning());
		model.setHistonumber(soapModel.getHistonumber());
		model.setKloetzelBuchRunning(soapModel.getKloetzelBuchRunning());
		model.setOid(soapModel.getOid());
		model.setBid(soapModel.getBid());
		model.setArea(soapModel.getArea());
		model.setType(soapModel.getType());
		model.setAcronym(soapModel.getAcronym());
		model.setText(soapModel.getText());
		model.setInfo(soapModel.getInfo());
		model.setCount(soapModel.getCount());
		model.setNumberOfPieces(soapModel.getNumberOfPieces());
		model.setKbStatus(soapModel.getKbStatus());
		model.setSort(soapModel.getSort());
		model.setColor(soapModel.getColor());
		model.setKbDate(soapModel.getKbDate());
		model.setDay(soapModel.getDay());
		model.setPocessinguser(soapModel.getPocessinguser());
		model.setOrganizationUnit(soapModel.getOrganizationUnit());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<KloetzelBuch> toModels(KloetzelBuchSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<KloetzelBuch> models = new ArrayList<KloetzelBuch>(soapModels.length);

		for (KloetzelBuchSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(at.graz.meduni.bibbox.medicaldataset.service.util.ServiceProps.get(
				"lock.expiration.time.at.graz.meduni.bibbox.medicaldataset.model.KloetzelBuch"));

	public KloetzelBuchModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _kloetzelBuchId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setKloetzelBuchId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _kloetzelBuchId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return KloetzelBuch.class;
	}

	@Override
	public String getModelClassName() {
		return KloetzelBuch.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("kloetzelBuchId", getKloetzelBuchId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("status", getStatus());
		attributes.put("statusByUserId", getStatusByUserId());
		attributes.put("statusByUserName", getStatusByUserName());
		attributes.put("statusDate", getStatusDate());
		attributes.put("medicalRecordId", getMedicalRecordId());
		attributes.put("histonumberStart", getHistonumberStart());
		attributes.put("histonumberEnd", getHistonumberEnd());
		attributes.put("histonumberRunning", getHistonumberRunning());
		attributes.put("histonumber", getHistonumber());
		attributes.put("kloetzelBuchRunning", getKloetzelBuchRunning());
		attributes.put("oid", getOid());
		attributes.put("bid", getBid());
		attributes.put("area", getArea());
		attributes.put("type", getType());
		attributes.put("acronym", getAcronym());
		attributes.put("text", getText());
		attributes.put("info", getInfo());
		attributes.put("count", getCount());
		attributes.put("numberOfPieces", getNumberOfPieces());
		attributes.put("kbStatus", getKbStatus());
		attributes.put("sort", getSort());
		attributes.put("color", getColor());
		attributes.put("kbDate", getKbDate());
		attributes.put("day", getDay());
		attributes.put("pocessinguser", getPocessinguser());
		attributes.put("organizationUnit", getOrganizationUnit());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long kloetzelBuchId = (Long)attributes.get("kloetzelBuchId");

		if (kloetzelBuchId != null) {
			setKloetzelBuchId(kloetzelBuchId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		Long statusByUserId = (Long)attributes.get("statusByUserId");

		if (statusByUserId != null) {
			setStatusByUserId(statusByUserId);
		}

		String statusByUserName = (String)attributes.get("statusByUserName");

		if (statusByUserName != null) {
			setStatusByUserName(statusByUserName);
		}

		Date statusDate = (Date)attributes.get("statusDate");

		if (statusDate != null) {
			setStatusDate(statusDate);
		}

		Long medicalRecordId = (Long)attributes.get("medicalRecordId");

		if (medicalRecordId != null) {
			setMedicalRecordId(medicalRecordId);
		}

		Long histonumberStart = (Long)attributes.get("histonumberStart");

		if (histonumberStart != null) {
			setHistonumberStart(histonumberStart);
		}

		Long histonumberEnd = (Long)attributes.get("histonumberEnd");

		if (histonumberEnd != null) {
			setHistonumberEnd(histonumberEnd);
		}

		Integer histonumberRunning = (Integer)attributes.get(
				"histonumberRunning");

		if (histonumberRunning != null) {
			setHistonumberRunning(histonumberRunning);
		}

		Long histonumber = (Long)attributes.get("histonumber");

		if (histonumber != null) {
			setHistonumber(histonumber);
		}

		Integer kloetzelBuchRunning = (Integer)attributes.get(
				"kloetzelBuchRunning");

		if (kloetzelBuchRunning != null) {
			setKloetzelBuchRunning(kloetzelBuchRunning);
		}

		String oid = (String)attributes.get("oid");

		if (oid != null) {
			setOid(oid);
		}

		String bid = (String)attributes.get("bid");

		if (bid != null) {
			setBid(bid);
		}

		String area = (String)attributes.get("area");

		if (area != null) {
			setArea(area);
		}

		String type = (String)attributes.get("type");

		if (type != null) {
			setType(type);
		}

		String acronym = (String)attributes.get("acronym");

		if (acronym != null) {
			setAcronym(acronym);
		}

		String text = (String)attributes.get("text");

		if (text != null) {
			setText(text);
		}

		String info = (String)attributes.get("info");

		if (info != null) {
			setInfo(info);
		}

		Integer count = (Integer)attributes.get("count");

		if (count != null) {
			setCount(count);
		}

		Integer numberOfPieces = (Integer)attributes.get("numberOfPieces");

		if (numberOfPieces != null) {
			setNumberOfPieces(numberOfPieces);
		}

		Integer kbStatus = (Integer)attributes.get("kbStatus");

		if (kbStatus != null) {
			setKbStatus(kbStatus);
		}

		Integer sort = (Integer)attributes.get("sort");

		if (sort != null) {
			setSort(sort);
		}

		String color = (String)attributes.get("color");

		if (color != null) {
			setColor(color);
		}

		Date kbDate = (Date)attributes.get("kbDate");

		if (kbDate != null) {
			setKbDate(kbDate);
		}

		String day = (String)attributes.get("day");

		if (day != null) {
			setDay(day);
		}

		String pocessinguser = (String)attributes.get("pocessinguser");

		if (pocessinguser != null) {
			setPocessinguser(pocessinguser);
		}

		String organizationUnit = (String)attributes.get("organizationUnit");

		if (organizationUnit != null) {
			setOrganizationUnit(organizationUnit);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getKloetzelBuchId() {
		return _kloetzelBuchId;
	}

	@Override
	public void setKloetzelBuchId(long kloetzelBuchId) {
		_columnBitmask = -1L;

		_kloetzelBuchId = kloetzelBuchId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return StringPool.BLANK;
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@JSON
	@Override
	public long getMedicalRecordId() {
		return _medicalRecordId;
	}

	@Override
	public void setMedicalRecordId(long medicalRecordId) {
		_columnBitmask |= MEDICALRECORDID_COLUMN_BITMASK;

		if (!_setOriginalMedicalRecordId) {
			_setOriginalMedicalRecordId = true;

			_originalMedicalRecordId = _medicalRecordId;
		}

		_medicalRecordId = medicalRecordId;
	}

	public long getOriginalMedicalRecordId() {
		return _originalMedicalRecordId;
	}

	@JSON
	@Override
	public long getHistonumberStart() {
		return _histonumberStart;
	}

	@Override
	public void setHistonumberStart(long histonumberStart) {
		_histonumberStart = histonumberStart;
	}

	@JSON
	@Override
	public long getHistonumberEnd() {
		return _histonumberEnd;
	}

	@Override
	public void setHistonumberEnd(long histonumberEnd) {
		_histonumberEnd = histonumberEnd;
	}

	@JSON
	@Override
	public int getHistonumberRunning() {
		return _histonumberRunning;
	}

	@Override
	public void setHistonumberRunning(int histonumberRunning) {
		_histonumberRunning = histonumberRunning;
	}

	@JSON
	@Override
	public long getHistonumber() {
		return _histonumber;
	}

	@Override
	public void setHistonumber(long histonumber) {
		_histonumber = histonumber;
	}

	@JSON
	@Override
	public int getKloetzelBuchRunning() {
		return _kloetzelBuchRunning;
	}

	@Override
	public void setKloetzelBuchRunning(int kloetzelBuchRunning) {
		_kloetzelBuchRunning = kloetzelBuchRunning;
	}

	@JSON
	@Override
	public String getOid() {
		if (_oid == null) {
			return StringPool.BLANK;
		}
		else {
			return _oid;
		}
	}

	@Override
	public void setOid(String oid) {
		_oid = oid;
	}

	@JSON
	@Override
	public String getBid() {
		if (_bid == null) {
			return StringPool.BLANK;
		}
		else {
			return _bid;
		}
	}

	@Override
	public void setBid(String bid) {
		_bid = bid;
	}

	@JSON
	@Override
	public String getArea() {
		if (_area == null) {
			return StringPool.BLANK;
		}
		else {
			return _area;
		}
	}

	@Override
	public void setArea(String area) {
		_area = area;
	}

	@JSON
	@Override
	public String getType() {
		if (_type == null) {
			return StringPool.BLANK;
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		_type = type;
	}

	@JSON
	@Override
	public String getAcronym() {
		if (_acronym == null) {
			return StringPool.BLANK;
		}
		else {
			return _acronym;
		}
	}

	@Override
	public void setAcronym(String acronym) {
		_acronym = acronym;
	}

	@JSON
	@Override
	public String getText() {
		if (_text == null) {
			return StringPool.BLANK;
		}
		else {
			return _text;
		}
	}

	@Override
	public void setText(String text) {
		_text = text;
	}

	@JSON
	@Override
	public String getInfo() {
		if (_info == null) {
			return StringPool.BLANK;
		}
		else {
			return _info;
		}
	}

	@Override
	public void setInfo(String info) {
		_info = info;
	}

	@JSON
	@Override
	public int getCount() {
		return _count;
	}

	@Override
	public void setCount(int count) {
		_count = count;
	}

	@JSON
	@Override
	public int getNumberOfPieces() {
		return _numberOfPieces;
	}

	@Override
	public void setNumberOfPieces(int numberOfPieces) {
		_numberOfPieces = numberOfPieces;
	}

	@JSON
	@Override
	public int getKbStatus() {
		return _kbStatus;
	}

	@Override
	public void setKbStatus(int kbStatus) {
		_kbStatus = kbStatus;
	}

	@JSON
	@Override
	public int getSort() {
		return _sort;
	}

	@Override
	public void setSort(int sort) {
		_sort = sort;
	}

	@JSON
	@Override
	public String getColor() {
		if (_color == null) {
			return StringPool.BLANK;
		}
		else {
			return _color;
		}
	}

	@Override
	public void setColor(String color) {
		_color = color;
	}

	@JSON
	@Override
	public Date getKbDate() {
		return _kbDate;
	}

	@Override
	public void setKbDate(Date kbDate) {
		_kbDate = kbDate;
	}

	@JSON
	@Override
	public String getDay() {
		if (_day == null) {
			return StringPool.BLANK;
		}
		else {
			return _day;
		}
	}

	@Override
	public void setDay(String day) {
		_day = day;
	}

	@JSON
	@Override
	public String getPocessinguser() {
		if (_pocessinguser == null) {
			return StringPool.BLANK;
		}
		else {
			return _pocessinguser;
		}
	}

	@Override
	public void setPocessinguser(String pocessinguser) {
		_pocessinguser = pocessinguser;
	}

	@JSON
	@Override
	public String getOrganizationUnit() {
		if (_organizationUnit == null) {
			return StringPool.BLANK;
		}
		else {
			return _organizationUnit;
		}
	}

	@Override
	public void setOrganizationUnit(String organizationUnit) {
		_organizationUnit = organizationUnit;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				KloetzelBuch.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			KloetzelBuch.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public KloetzelBuch toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (KloetzelBuch)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		KloetzelBuchImpl kloetzelBuchImpl = new KloetzelBuchImpl();

		kloetzelBuchImpl.setUuid(getUuid());
		kloetzelBuchImpl.setKloetzelBuchId(getKloetzelBuchId());
		kloetzelBuchImpl.setGroupId(getGroupId());
		kloetzelBuchImpl.setCompanyId(getCompanyId());
		kloetzelBuchImpl.setUserId(getUserId());
		kloetzelBuchImpl.setUserName(getUserName());
		kloetzelBuchImpl.setCreateDate(getCreateDate());
		kloetzelBuchImpl.setModifiedDate(getModifiedDate());
		kloetzelBuchImpl.setStatus(getStatus());
		kloetzelBuchImpl.setStatusByUserId(getStatusByUserId());
		kloetzelBuchImpl.setStatusByUserName(getStatusByUserName());
		kloetzelBuchImpl.setStatusDate(getStatusDate());
		kloetzelBuchImpl.setMedicalRecordId(getMedicalRecordId());
		kloetzelBuchImpl.setHistonumberStart(getHistonumberStart());
		kloetzelBuchImpl.setHistonumberEnd(getHistonumberEnd());
		kloetzelBuchImpl.setHistonumberRunning(getHistonumberRunning());
		kloetzelBuchImpl.setHistonumber(getHistonumber());
		kloetzelBuchImpl.setKloetzelBuchRunning(getKloetzelBuchRunning());
		kloetzelBuchImpl.setOid(getOid());
		kloetzelBuchImpl.setBid(getBid());
		kloetzelBuchImpl.setArea(getArea());
		kloetzelBuchImpl.setType(getType());
		kloetzelBuchImpl.setAcronym(getAcronym());
		kloetzelBuchImpl.setText(getText());
		kloetzelBuchImpl.setInfo(getInfo());
		kloetzelBuchImpl.setCount(getCount());
		kloetzelBuchImpl.setNumberOfPieces(getNumberOfPieces());
		kloetzelBuchImpl.setKbStatus(getKbStatus());
		kloetzelBuchImpl.setSort(getSort());
		kloetzelBuchImpl.setColor(getColor());
		kloetzelBuchImpl.setKbDate(getKbDate());
		kloetzelBuchImpl.setDay(getDay());
		kloetzelBuchImpl.setPocessinguser(getPocessinguser());
		kloetzelBuchImpl.setOrganizationUnit(getOrganizationUnit());

		kloetzelBuchImpl.resetOriginalValues();

		return kloetzelBuchImpl;
	}

	@Override
	public int compareTo(KloetzelBuch kloetzelBuch) {
		int value = 0;

		if (getKloetzelBuchId() < kloetzelBuch.getKloetzelBuchId()) {
			value = -1;
		}
		else if (getKloetzelBuchId() > kloetzelBuch.getKloetzelBuchId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof KloetzelBuch)) {
			return false;
		}

		KloetzelBuch kloetzelBuch = (KloetzelBuch)obj;

		long primaryKey = kloetzelBuch.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		KloetzelBuchModelImpl kloetzelBuchModelImpl = this;

		kloetzelBuchModelImpl._originalUuid = kloetzelBuchModelImpl._uuid;

		kloetzelBuchModelImpl._originalGroupId = kloetzelBuchModelImpl._groupId;

		kloetzelBuchModelImpl._setOriginalGroupId = false;

		kloetzelBuchModelImpl._originalCompanyId = kloetzelBuchModelImpl._companyId;

		kloetzelBuchModelImpl._setOriginalCompanyId = false;

		kloetzelBuchModelImpl._setModifiedDate = false;

		kloetzelBuchModelImpl._originalMedicalRecordId = kloetzelBuchModelImpl._medicalRecordId;

		kloetzelBuchModelImpl._setOriginalMedicalRecordId = false;

		kloetzelBuchModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<KloetzelBuch> toCacheModel() {
		KloetzelBuchCacheModel kloetzelBuchCacheModel = new KloetzelBuchCacheModel();

		kloetzelBuchCacheModel.uuid = getUuid();

		String uuid = kloetzelBuchCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			kloetzelBuchCacheModel.uuid = null;
		}

		kloetzelBuchCacheModel.kloetzelBuchId = getKloetzelBuchId();

		kloetzelBuchCacheModel.groupId = getGroupId();

		kloetzelBuchCacheModel.companyId = getCompanyId();

		kloetzelBuchCacheModel.userId = getUserId();

		kloetzelBuchCacheModel.userName = getUserName();

		String userName = kloetzelBuchCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			kloetzelBuchCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			kloetzelBuchCacheModel.createDate = createDate.getTime();
		}
		else {
			kloetzelBuchCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			kloetzelBuchCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			kloetzelBuchCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		kloetzelBuchCacheModel.status = getStatus();

		kloetzelBuchCacheModel.statusByUserId = getStatusByUserId();

		kloetzelBuchCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = kloetzelBuchCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			kloetzelBuchCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			kloetzelBuchCacheModel.statusDate = statusDate.getTime();
		}
		else {
			kloetzelBuchCacheModel.statusDate = Long.MIN_VALUE;
		}

		kloetzelBuchCacheModel.medicalRecordId = getMedicalRecordId();

		kloetzelBuchCacheModel.histonumberStart = getHistonumberStart();

		kloetzelBuchCacheModel.histonumberEnd = getHistonumberEnd();

		kloetzelBuchCacheModel.histonumberRunning = getHistonumberRunning();

		kloetzelBuchCacheModel.histonumber = getHistonumber();

		kloetzelBuchCacheModel.kloetzelBuchRunning = getKloetzelBuchRunning();

		kloetzelBuchCacheModel.oid = getOid();

		String oid = kloetzelBuchCacheModel.oid;

		if ((oid != null) && (oid.length() == 0)) {
			kloetzelBuchCacheModel.oid = null;
		}

		kloetzelBuchCacheModel.bid = getBid();

		String bid = kloetzelBuchCacheModel.bid;

		if ((bid != null) && (bid.length() == 0)) {
			kloetzelBuchCacheModel.bid = null;
		}

		kloetzelBuchCacheModel.area = getArea();

		String area = kloetzelBuchCacheModel.area;

		if ((area != null) && (area.length() == 0)) {
			kloetzelBuchCacheModel.area = null;
		}

		kloetzelBuchCacheModel.type = getType();

		String type = kloetzelBuchCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			kloetzelBuchCacheModel.type = null;
		}

		kloetzelBuchCacheModel.acronym = getAcronym();

		String acronym = kloetzelBuchCacheModel.acronym;

		if ((acronym != null) && (acronym.length() == 0)) {
			kloetzelBuchCacheModel.acronym = null;
		}

		kloetzelBuchCacheModel.text = getText();

		String text = kloetzelBuchCacheModel.text;

		if ((text != null) && (text.length() == 0)) {
			kloetzelBuchCacheModel.text = null;
		}

		kloetzelBuchCacheModel.info = getInfo();

		String info = kloetzelBuchCacheModel.info;

		if ((info != null) && (info.length() == 0)) {
			kloetzelBuchCacheModel.info = null;
		}

		kloetzelBuchCacheModel.count = getCount();

		kloetzelBuchCacheModel.numberOfPieces = getNumberOfPieces();

		kloetzelBuchCacheModel.kbStatus = getKbStatus();

		kloetzelBuchCacheModel.sort = getSort();

		kloetzelBuchCacheModel.color = getColor();

		String color = kloetzelBuchCacheModel.color;

		if ((color != null) && (color.length() == 0)) {
			kloetzelBuchCacheModel.color = null;
		}

		Date kbDate = getKbDate();

		if (kbDate != null) {
			kloetzelBuchCacheModel.kbDate = kbDate.getTime();
		}
		else {
			kloetzelBuchCacheModel.kbDate = Long.MIN_VALUE;
		}

		kloetzelBuchCacheModel.day = getDay();

		String day = kloetzelBuchCacheModel.day;

		if ((day != null) && (day.length() == 0)) {
			kloetzelBuchCacheModel.day = null;
		}

		kloetzelBuchCacheModel.pocessinguser = getPocessinguser();

		String pocessinguser = kloetzelBuchCacheModel.pocessinguser;

		if ((pocessinguser != null) && (pocessinguser.length() == 0)) {
			kloetzelBuchCacheModel.pocessinguser = null;
		}

		kloetzelBuchCacheModel.organizationUnit = getOrganizationUnit();

		String organizationUnit = kloetzelBuchCacheModel.organizationUnit;

		if ((organizationUnit != null) && (organizationUnit.length() == 0)) {
			kloetzelBuchCacheModel.organizationUnit = null;
		}

		return kloetzelBuchCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(69);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", kloetzelBuchId=");
		sb.append(getKloetzelBuchId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", statusByUserId=");
		sb.append(getStatusByUserId());
		sb.append(", statusByUserName=");
		sb.append(getStatusByUserName());
		sb.append(", statusDate=");
		sb.append(getStatusDate());
		sb.append(", medicalRecordId=");
		sb.append(getMedicalRecordId());
		sb.append(", histonumberStart=");
		sb.append(getHistonumberStart());
		sb.append(", histonumberEnd=");
		sb.append(getHistonumberEnd());
		sb.append(", histonumberRunning=");
		sb.append(getHistonumberRunning());
		sb.append(", histonumber=");
		sb.append(getHistonumber());
		sb.append(", kloetzelBuchRunning=");
		sb.append(getKloetzelBuchRunning());
		sb.append(", oid=");
		sb.append(getOid());
		sb.append(", bid=");
		sb.append(getBid());
		sb.append(", area=");
		sb.append(getArea());
		sb.append(", type=");
		sb.append(getType());
		sb.append(", acronym=");
		sb.append(getAcronym());
		sb.append(", text=");
		sb.append(getText());
		sb.append(", info=");
		sb.append(getInfo());
		sb.append(", count=");
		sb.append(getCount());
		sb.append(", numberOfPieces=");
		sb.append(getNumberOfPieces());
		sb.append(", kbStatus=");
		sb.append(getKbStatus());
		sb.append(", sort=");
		sb.append(getSort());
		sb.append(", color=");
		sb.append(getColor());
		sb.append(", kbDate=");
		sb.append(getKbDate());
		sb.append(", day=");
		sb.append(getDay());
		sb.append(", pocessinguser=");
		sb.append(getPocessinguser());
		sb.append(", organizationUnit=");
		sb.append(getOrganizationUnit());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(106);

		sb.append("<model><model-name>");
		sb.append("at.graz.meduni.bibbox.medicaldataset.model.KloetzelBuch");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kloetzelBuchId</column-name><column-value><![CDATA[");
		sb.append(getKloetzelBuchId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserId</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserName</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusDate</column-name><column-value><![CDATA[");
		sb.append(getStatusDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>medicalRecordId</column-name><column-value><![CDATA[");
		sb.append(getMedicalRecordId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>histonumberStart</column-name><column-value><![CDATA[");
		sb.append(getHistonumberStart());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>histonumberEnd</column-name><column-value><![CDATA[");
		sb.append(getHistonumberEnd());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>histonumberRunning</column-name><column-value><![CDATA[");
		sb.append(getHistonumberRunning());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>histonumber</column-name><column-value><![CDATA[");
		sb.append(getHistonumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kloetzelBuchRunning</column-name><column-value><![CDATA[");
		sb.append(getKloetzelBuchRunning());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>oid</column-name><column-value><![CDATA[");
		sb.append(getOid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bid</column-name><column-value><![CDATA[");
		sb.append(getBid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>area</column-name><column-value><![CDATA[");
		sb.append(getArea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type</column-name><column-value><![CDATA[");
		sb.append(getType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>acronym</column-name><column-value><![CDATA[");
		sb.append(getAcronym());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>text</column-name><column-value><![CDATA[");
		sb.append(getText());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>info</column-name><column-value><![CDATA[");
		sb.append(getInfo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>count</column-name><column-value><![CDATA[");
		sb.append(getCount());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>numberOfPieces</column-name><column-value><![CDATA[");
		sb.append(getNumberOfPieces());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kbStatus</column-name><column-value><![CDATA[");
		sb.append(getKbStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sort</column-name><column-value><![CDATA[");
		sb.append(getSort());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>color</column-name><column-value><![CDATA[");
		sb.append(getColor());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kbDate</column-name><column-value><![CDATA[");
		sb.append(getKbDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>day</column-name><column-value><![CDATA[");
		sb.append(getDay());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>pocessinguser</column-name><column-value><![CDATA[");
		sb.append(getPocessinguser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>organizationUnit</column-name><column-value><![CDATA[");
		sb.append(getOrganizationUnit());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = KloetzelBuch.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			KloetzelBuch.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _kloetzelBuchId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private long _medicalRecordId;
	private long _originalMedicalRecordId;
	private boolean _setOriginalMedicalRecordId;
	private long _histonumberStart;
	private long _histonumberEnd;
	private int _histonumberRunning;
	private long _histonumber;
	private int _kloetzelBuchRunning;
	private String _oid;
	private String _bid;
	private String _area;
	private String _type;
	private String _acronym;
	private String _text;
	private String _info;
	private int _count;
	private int _numberOfPieces;
	private int _kbStatus;
	private int _sort;
	private String _color;
	private Date _kbDate;
	private String _day;
	private String _pocessinguser;
	private String _organizationUnit;
	private long _columnBitmask;
	private KloetzelBuch _escapedModel;
}