/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.bibbox.medicaldataset.model.impl;

import aQute.bnd.annotation.ProviderType;

import at.graz.meduni.bibbox.medicaldataset.model.MedicalRecord;
import at.graz.meduni.bibbox.medicaldataset.model.MedicalRecordModel;
import at.graz.meduni.bibbox.medicaldataset.model.MedicalRecordSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the MedicalRecord service. Represents a row in the &quot;FOO_MedicalRecord&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link MedicalRecordModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MedicalRecordImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MedicalRecordImpl
 * @see MedicalRecord
 * @see MedicalRecordModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class MedicalRecordModelImpl extends BaseModelImpl<MedicalRecord>
	implements MedicalRecordModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a medical record model instance should use the {@link MedicalRecord} interface instead.
	 */
	public static final String TABLE_NAME = "FOO_MedicalRecord";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "medicalRecordId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "status", Types.INTEGER },
			{ "statusByUserId", Types.BIGINT },
			{ "statusByUserName", Types.VARCHAR },
			{ "statusDate", Types.TIMESTAMP },
			{ "importMedicalDataSetId", Types.BIGINT },
			{ "histonumberStart", Types.BIGINT },
			{ "histonumberEnd", Types.BIGINT },
			{ "histonumberRunning", Types.INTEGER },
			{ "iNumber", Types.BIGINT },
			{ "vPatientId", Types.BIGINT },
			{ "vHistonNumber", Types.BIGINT },
			{ "area", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("medicalRecordId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("importMedicalDataSetId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("histonumberStart", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("histonumberEnd", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("histonumberRunning", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("iNumber", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("vPatientId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("vHistonNumber", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("area", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table FOO_MedicalRecord (uuid_ VARCHAR(75) null,medicalRecordId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,importMedicalDataSetId LONG,histonumberStart LONG,histonumberEnd LONG,histonumberRunning INTEGER,iNumber LONG,vPatientId LONG,vHistonNumber LONG,area VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table FOO_MedicalRecord";
	public static final String ORDER_BY_JPQL = " ORDER BY medicalRecord.medicalRecordId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY FOO_MedicalRecord.medicalRecordId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(at.graz.meduni.bibbox.medicaldataset.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.at.graz.meduni.bibbox.medicaldataset.model.MedicalRecord"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(at.graz.meduni.bibbox.medicaldataset.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.at.graz.meduni.bibbox.medicaldataset.model.MedicalRecord"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(at.graz.meduni.bibbox.medicaldataset.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.at.graz.meduni.bibbox.medicaldataset.model.MedicalRecord"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long GROUPID_COLUMN_BITMASK = 2L;
	public static final long INUMBER_COLUMN_BITMASK = 4L;
	public static final long IMPORTMEDICALDATASETID_COLUMN_BITMASK = 8L;
	public static final long UUID_COLUMN_BITMASK = 16L;
	public static final long MEDICALRECORDID_COLUMN_BITMASK = 32L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static MedicalRecord toModel(MedicalRecordSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		MedicalRecord model = new MedicalRecordImpl();

		model.setUuid(soapModel.getUuid());
		model.setMedicalRecordId(soapModel.getMedicalRecordId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setImportMedicalDataSetId(soapModel.getImportMedicalDataSetId());
		model.setHistonumberStart(soapModel.getHistonumberStart());
		model.setHistonumberEnd(soapModel.getHistonumberEnd());
		model.setHistonumberRunning(soapModel.getHistonumberRunning());
		model.setINumber(soapModel.getINumber());
		model.setVPatientId(soapModel.getVPatientId());
		model.setVHistonNumber(soapModel.getVHistonNumber());
		model.setArea(soapModel.getArea());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<MedicalRecord> toModels(MedicalRecordSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<MedicalRecord> models = new ArrayList<MedicalRecord>(soapModels.length);

		for (MedicalRecordSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(at.graz.meduni.bibbox.medicaldataset.service.util.ServiceProps.get(
				"lock.expiration.time.at.graz.meduni.bibbox.medicaldataset.model.MedicalRecord"));

	public MedicalRecordModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _medicalRecordId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMedicalRecordId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _medicalRecordId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MedicalRecord.class;
	}

	@Override
	public String getModelClassName() {
		return MedicalRecord.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("medicalRecordId", getMedicalRecordId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("status", getStatus());
		attributes.put("statusByUserId", getStatusByUserId());
		attributes.put("statusByUserName", getStatusByUserName());
		attributes.put("statusDate", getStatusDate());
		attributes.put("importMedicalDataSetId", getImportMedicalDataSetId());
		attributes.put("histonumberStart", getHistonumberStart());
		attributes.put("histonumberEnd", getHistonumberEnd());
		attributes.put("histonumberRunning", getHistonumberRunning());
		attributes.put("iNumber", getINumber());
		attributes.put("vPatientId", getVPatientId());
		attributes.put("vHistonNumber", getVHistonNumber());
		attributes.put("area", getArea());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long medicalRecordId = (Long)attributes.get("medicalRecordId");

		if (medicalRecordId != null) {
			setMedicalRecordId(medicalRecordId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		Long statusByUserId = (Long)attributes.get("statusByUserId");

		if (statusByUserId != null) {
			setStatusByUserId(statusByUserId);
		}

		String statusByUserName = (String)attributes.get("statusByUserName");

		if (statusByUserName != null) {
			setStatusByUserName(statusByUserName);
		}

		Date statusDate = (Date)attributes.get("statusDate");

		if (statusDate != null) {
			setStatusDate(statusDate);
		}

		Long importMedicalDataSetId = (Long)attributes.get(
				"importMedicalDataSetId");

		if (importMedicalDataSetId != null) {
			setImportMedicalDataSetId(importMedicalDataSetId);
		}

		Long histonumberStart = (Long)attributes.get("histonumberStart");

		if (histonumberStart != null) {
			setHistonumberStart(histonumberStart);
		}

		Long histonumberEnd = (Long)attributes.get("histonumberEnd");

		if (histonumberEnd != null) {
			setHistonumberEnd(histonumberEnd);
		}

		Integer histonumberRunning = (Integer)attributes.get(
				"histonumberRunning");

		if (histonumberRunning != null) {
			setHistonumberRunning(histonumberRunning);
		}

		Long iNumber = (Long)attributes.get("iNumber");

		if (iNumber != null) {
			setINumber(iNumber);
		}

		Long vPatientId = (Long)attributes.get("vPatientId");

		if (vPatientId != null) {
			setVPatientId(vPatientId);
		}

		Long vHistonNumber = (Long)attributes.get("vHistonNumber");

		if (vHistonNumber != null) {
			setVHistonNumber(vHistonNumber);
		}

		String area = (String)attributes.get("area");

		if (area != null) {
			setArea(area);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getMedicalRecordId() {
		return _medicalRecordId;
	}

	@Override
	public void setMedicalRecordId(long medicalRecordId) {
		_columnBitmask = -1L;

		_medicalRecordId = medicalRecordId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return StringPool.BLANK;
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@JSON
	@Override
	public long getImportMedicalDataSetId() {
		return _importMedicalDataSetId;
	}

	@Override
	public void setImportMedicalDataSetId(long importMedicalDataSetId) {
		_columnBitmask |= IMPORTMEDICALDATASETID_COLUMN_BITMASK;

		if (!_setOriginalImportMedicalDataSetId) {
			_setOriginalImportMedicalDataSetId = true;

			_originalImportMedicalDataSetId = _importMedicalDataSetId;
		}

		_importMedicalDataSetId = importMedicalDataSetId;
	}

	public long getOriginalImportMedicalDataSetId() {
		return _originalImportMedicalDataSetId;
	}

	@JSON
	@Override
	public long getHistonumberStart() {
		return _histonumberStart;
	}

	@Override
	public void setHistonumberStart(long histonumberStart) {
		_histonumberStart = histonumberStart;
	}

	@JSON
	@Override
	public long getHistonumberEnd() {
		return _histonumberEnd;
	}

	@Override
	public void setHistonumberEnd(long histonumberEnd) {
		_histonumberEnd = histonumberEnd;
	}

	@JSON
	@Override
	public int getHistonumberRunning() {
		return _histonumberRunning;
	}

	@Override
	public void setHistonumberRunning(int histonumberRunning) {
		_histonumberRunning = histonumberRunning;
	}

	@JSON
	@Override
	public long getINumber() {
		return _iNumber;
	}

	@Override
	public void setINumber(long iNumber) {
		_columnBitmask |= INUMBER_COLUMN_BITMASK;

		if (!_setOriginalINumber) {
			_setOriginalINumber = true;

			_originalINumber = _iNumber;
		}

		_iNumber = iNumber;
	}

	public long getOriginalINumber() {
		return _originalINumber;
	}

	@JSON
	@Override
	public long getVPatientId() {
		return _vPatientId;
	}

	@Override
	public void setVPatientId(long vPatientId) {
		_vPatientId = vPatientId;
	}

	@JSON
	@Override
	public long getVHistonNumber() {
		return _vHistonNumber;
	}

	@Override
	public void setVHistonNumber(long vHistonNumber) {
		_vHistonNumber = vHistonNumber;
	}

	@JSON
	@Override
	public String getArea() {
		if (_area == null) {
			return StringPool.BLANK;
		}
		else {
			return _area;
		}
	}

	@Override
	public void setArea(String area) {
		_area = area;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				MedicalRecord.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			MedicalRecord.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MedicalRecord toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (MedicalRecord)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MedicalRecordImpl medicalRecordImpl = new MedicalRecordImpl();

		medicalRecordImpl.setUuid(getUuid());
		medicalRecordImpl.setMedicalRecordId(getMedicalRecordId());
		medicalRecordImpl.setGroupId(getGroupId());
		medicalRecordImpl.setCompanyId(getCompanyId());
		medicalRecordImpl.setUserId(getUserId());
		medicalRecordImpl.setUserName(getUserName());
		medicalRecordImpl.setCreateDate(getCreateDate());
		medicalRecordImpl.setModifiedDate(getModifiedDate());
		medicalRecordImpl.setStatus(getStatus());
		medicalRecordImpl.setStatusByUserId(getStatusByUserId());
		medicalRecordImpl.setStatusByUserName(getStatusByUserName());
		medicalRecordImpl.setStatusDate(getStatusDate());
		medicalRecordImpl.setImportMedicalDataSetId(getImportMedicalDataSetId());
		medicalRecordImpl.setHistonumberStart(getHistonumberStart());
		medicalRecordImpl.setHistonumberEnd(getHistonumberEnd());
		medicalRecordImpl.setHistonumberRunning(getHistonumberRunning());
		medicalRecordImpl.setINumber(getINumber());
		medicalRecordImpl.setVPatientId(getVPatientId());
		medicalRecordImpl.setVHistonNumber(getVHistonNumber());
		medicalRecordImpl.setArea(getArea());

		medicalRecordImpl.resetOriginalValues();

		return medicalRecordImpl;
	}

	@Override
	public int compareTo(MedicalRecord medicalRecord) {
		int value = 0;

		if (getMedicalRecordId() < medicalRecord.getMedicalRecordId()) {
			value = -1;
		}
		else if (getMedicalRecordId() > medicalRecord.getMedicalRecordId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof MedicalRecord)) {
			return false;
		}

		MedicalRecord medicalRecord = (MedicalRecord)obj;

		long primaryKey = medicalRecord.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		MedicalRecordModelImpl medicalRecordModelImpl = this;

		medicalRecordModelImpl._originalUuid = medicalRecordModelImpl._uuid;

		medicalRecordModelImpl._originalGroupId = medicalRecordModelImpl._groupId;

		medicalRecordModelImpl._setOriginalGroupId = false;

		medicalRecordModelImpl._originalCompanyId = medicalRecordModelImpl._companyId;

		medicalRecordModelImpl._setOriginalCompanyId = false;

		medicalRecordModelImpl._setModifiedDate = false;

		medicalRecordModelImpl._originalImportMedicalDataSetId = medicalRecordModelImpl._importMedicalDataSetId;

		medicalRecordModelImpl._setOriginalImportMedicalDataSetId = false;

		medicalRecordModelImpl._originalINumber = medicalRecordModelImpl._iNumber;

		medicalRecordModelImpl._setOriginalINumber = false;

		medicalRecordModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<MedicalRecord> toCacheModel() {
		MedicalRecordCacheModel medicalRecordCacheModel = new MedicalRecordCacheModel();

		medicalRecordCacheModel.uuid = getUuid();

		String uuid = medicalRecordCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			medicalRecordCacheModel.uuid = null;
		}

		medicalRecordCacheModel.medicalRecordId = getMedicalRecordId();

		medicalRecordCacheModel.groupId = getGroupId();

		medicalRecordCacheModel.companyId = getCompanyId();

		medicalRecordCacheModel.userId = getUserId();

		medicalRecordCacheModel.userName = getUserName();

		String userName = medicalRecordCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			medicalRecordCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			medicalRecordCacheModel.createDate = createDate.getTime();
		}
		else {
			medicalRecordCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			medicalRecordCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			medicalRecordCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		medicalRecordCacheModel.status = getStatus();

		medicalRecordCacheModel.statusByUserId = getStatusByUserId();

		medicalRecordCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = medicalRecordCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			medicalRecordCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			medicalRecordCacheModel.statusDate = statusDate.getTime();
		}
		else {
			medicalRecordCacheModel.statusDate = Long.MIN_VALUE;
		}

		medicalRecordCacheModel.importMedicalDataSetId = getImportMedicalDataSetId();

		medicalRecordCacheModel.histonumberStart = getHistonumberStart();

		medicalRecordCacheModel.histonumberEnd = getHistonumberEnd();

		medicalRecordCacheModel.histonumberRunning = getHistonumberRunning();

		medicalRecordCacheModel.iNumber = getINumber();

		medicalRecordCacheModel.vPatientId = getVPatientId();

		medicalRecordCacheModel.vHistonNumber = getVHistonNumber();

		medicalRecordCacheModel.area = getArea();

		String area = medicalRecordCacheModel.area;

		if ((area != null) && (area.length() == 0)) {
			medicalRecordCacheModel.area = null;
		}

		return medicalRecordCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(41);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", medicalRecordId=");
		sb.append(getMedicalRecordId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", statusByUserId=");
		sb.append(getStatusByUserId());
		sb.append(", statusByUserName=");
		sb.append(getStatusByUserName());
		sb.append(", statusDate=");
		sb.append(getStatusDate());
		sb.append(", importMedicalDataSetId=");
		sb.append(getImportMedicalDataSetId());
		sb.append(", histonumberStart=");
		sb.append(getHistonumberStart());
		sb.append(", histonumberEnd=");
		sb.append(getHistonumberEnd());
		sb.append(", histonumberRunning=");
		sb.append(getHistonumberRunning());
		sb.append(", iNumber=");
		sb.append(getINumber());
		sb.append(", vPatientId=");
		sb.append(getVPatientId());
		sb.append(", vHistonNumber=");
		sb.append(getVHistonNumber());
		sb.append(", area=");
		sb.append(getArea());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(64);

		sb.append("<model><model-name>");
		sb.append("at.graz.meduni.bibbox.medicaldataset.model.MedicalRecord");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>medicalRecordId</column-name><column-value><![CDATA[");
		sb.append(getMedicalRecordId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserId</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserName</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusDate</column-name><column-value><![CDATA[");
		sb.append(getStatusDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>importMedicalDataSetId</column-name><column-value><![CDATA[");
		sb.append(getImportMedicalDataSetId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>histonumberStart</column-name><column-value><![CDATA[");
		sb.append(getHistonumberStart());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>histonumberEnd</column-name><column-value><![CDATA[");
		sb.append(getHistonumberEnd());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>histonumberRunning</column-name><column-value><![CDATA[");
		sb.append(getHistonumberRunning());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>iNumber</column-name><column-value><![CDATA[");
		sb.append(getINumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vPatientId</column-name><column-value><![CDATA[");
		sb.append(getVPatientId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vHistonNumber</column-name><column-value><![CDATA[");
		sb.append(getVHistonNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>area</column-name><column-value><![CDATA[");
		sb.append(getArea());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = MedicalRecord.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			MedicalRecord.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _medicalRecordId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private long _importMedicalDataSetId;
	private long _originalImportMedicalDataSetId;
	private boolean _setOriginalImportMedicalDataSetId;
	private long _histonumberStart;
	private long _histonumberEnd;
	private int _histonumberRunning;
	private long _iNumber;
	private long _originalINumber;
	private boolean _setOriginalINumber;
	private long _vPatientId;
	private long _vHistonNumber;
	private String _area;
	private long _columnBitmask;
	private MedicalRecord _escapedModel;
}