/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.bibbox.digitalpathology.model.impl;

import aQute.bnd.annotation.ProviderType;

import at.graz.meduni.bibbox.digitalpathology.model.wsi;
import at.graz.meduni.bibbox.digitalpathology.model.wsiModel;
import at.graz.meduni.bibbox.digitalpathology.model.wsiSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the wsi service. Represents a row in the &quot;DP_wsi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link wsiModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link wsiImpl}.
 * </p>
 *
 * @author robert
 * @see wsiImpl
 * @see wsi
 * @see wsiModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class wsiModelImpl extends BaseModelImpl<wsi> implements wsiModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a wsi model instance should use the {@link wsi} interface instead.
	 */
	public static final String TABLE_NAME = "DP_wsi";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "wsiId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "status", Types.INTEGER },
			{ "statusByUserId", Types.BIGINT },
			{ "statusByUserName", Types.VARCHAR },
			{ "statusDate", Types.TIMESTAMP },
			{ "filename", Types.VARCHAR },
			{ "hashmrxs", Types.VARCHAR },
			{ "scanstart", Types.TIMESTAMP },
			{ "scanduration", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("wsiId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("filename", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("hashmrxs", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("scanstart", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("scanduration", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table DP_wsi (uuid_ VARCHAR(75) null,wsiId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,filename VARCHAR(75) null,hashmrxs VARCHAR(75) null,scanstart DATE null,scanduration LONG)";
	public static final String TABLE_SQL_DROP = "drop table DP_wsi";
	public static final String ORDER_BY_JPQL = " ORDER BY wsi.scanstart ASC";
	public static final String ORDER_BY_SQL = " ORDER BY DP_wsi.scanstart ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(at.graz.meduni.bibbox.digitalpathology.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.at.graz.meduni.bibbox.digitalpathology.model.wsi"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(at.graz.meduni.bibbox.digitalpathology.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.at.graz.meduni.bibbox.digitalpathology.model.wsi"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(at.graz.meduni.bibbox.digitalpathology.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.at.graz.meduni.bibbox.digitalpathology.model.wsi"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long FILENAME_COLUMN_BITMASK = 2L;
	public static final long GROUPID_COLUMN_BITMASK = 4L;
	public static final long UUID_COLUMN_BITMASK = 8L;
	public static final long SCANSTART_COLUMN_BITMASK = 16L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static wsi toModel(wsiSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		wsi model = new wsiImpl();

		model.setUuid(soapModel.getUuid());
		model.setWsiId(soapModel.getWsiId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setFilename(soapModel.getFilename());
		model.setHashmrxs(soapModel.getHashmrxs());
		model.setScanstart(soapModel.getScanstart());
		model.setScanduration(soapModel.getScanduration());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<wsi> toModels(wsiSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<wsi> models = new ArrayList<wsi>(soapModels.length);

		for (wsiSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(at.graz.meduni.bibbox.digitalpathology.service.util.ServiceProps.get(
				"lock.expiration.time.at.graz.meduni.bibbox.digitalpathology.model.wsi"));

	public wsiModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _wsiId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setWsiId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _wsiId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return wsi.class;
	}

	@Override
	public String getModelClassName() {
		return wsi.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("wsiId", getWsiId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("status", getStatus());
		attributes.put("statusByUserId", getStatusByUserId());
		attributes.put("statusByUserName", getStatusByUserName());
		attributes.put("statusDate", getStatusDate());
		attributes.put("filename", getFilename());
		attributes.put("hashmrxs", getHashmrxs());
		attributes.put("scanstart", getScanstart());
		attributes.put("scanduration", getScanduration());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long wsiId = (Long)attributes.get("wsiId");

		if (wsiId != null) {
			setWsiId(wsiId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		Long statusByUserId = (Long)attributes.get("statusByUserId");

		if (statusByUserId != null) {
			setStatusByUserId(statusByUserId);
		}

		String statusByUserName = (String)attributes.get("statusByUserName");

		if (statusByUserName != null) {
			setStatusByUserName(statusByUserName);
		}

		Date statusDate = (Date)attributes.get("statusDate");

		if (statusDate != null) {
			setStatusDate(statusDate);
		}

		String filename = (String)attributes.get("filename");

		if (filename != null) {
			setFilename(filename);
		}

		String hashmrxs = (String)attributes.get("hashmrxs");

		if (hashmrxs != null) {
			setHashmrxs(hashmrxs);
		}

		Date scanstart = (Date)attributes.get("scanstart");

		if (scanstart != null) {
			setScanstart(scanstart);
		}

		Long scanduration = (Long)attributes.get("scanduration");

		if (scanduration != null) {
			setScanduration(scanduration);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getWsiId() {
		return _wsiId;
	}

	@Override
	public void setWsiId(long wsiId) {
		_wsiId = wsiId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return StringPool.BLANK;
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getFilename() {
		if (_filename == null) {
			return StringPool.BLANK;
		}
		else {
			return _filename;
		}
	}

	@Override
	public void setFilename(String filename) {
		_columnBitmask |= FILENAME_COLUMN_BITMASK;

		if (_originalFilename == null) {
			_originalFilename = _filename;
		}

		_filename = filename;
	}

	public String getOriginalFilename() {
		return GetterUtil.getString(_originalFilename);
	}

	@JSON
	@Override
	public String getHashmrxs() {
		if (_hashmrxs == null) {
			return StringPool.BLANK;
		}
		else {
			return _hashmrxs;
		}
	}

	@Override
	public void setHashmrxs(String hashmrxs) {
		_hashmrxs = hashmrxs;
	}

	@JSON
	@Override
	public Date getScanstart() {
		return _scanstart;
	}

	@Override
	public void setScanstart(Date scanstart) {
		_columnBitmask = -1L;

		_scanstart = scanstart;
	}

	@JSON
	@Override
	public long getScanduration() {
		return _scanduration;
	}

	@Override
	public void setScanduration(long scanduration) {
		_scanduration = scanduration;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				wsi.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			wsi.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public wsi toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (wsi)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		wsiImpl wsiImpl = new wsiImpl();

		wsiImpl.setUuid(getUuid());
		wsiImpl.setWsiId(getWsiId());
		wsiImpl.setGroupId(getGroupId());
		wsiImpl.setCompanyId(getCompanyId());
		wsiImpl.setUserId(getUserId());
		wsiImpl.setUserName(getUserName());
		wsiImpl.setCreateDate(getCreateDate());
		wsiImpl.setModifiedDate(getModifiedDate());
		wsiImpl.setStatus(getStatus());
		wsiImpl.setStatusByUserId(getStatusByUserId());
		wsiImpl.setStatusByUserName(getStatusByUserName());
		wsiImpl.setStatusDate(getStatusDate());
		wsiImpl.setFilename(getFilename());
		wsiImpl.setHashmrxs(getHashmrxs());
		wsiImpl.setScanstart(getScanstart());
		wsiImpl.setScanduration(getScanduration());

		wsiImpl.resetOriginalValues();

		return wsiImpl;
	}

	@Override
	public int compareTo(wsi wsi) {
		int value = 0;

		value = DateUtil.compareTo(getScanstart(), wsi.getScanstart());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof wsi)) {
			return false;
		}

		wsi wsi = (wsi)obj;

		long primaryKey = wsi.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		wsiModelImpl wsiModelImpl = this;

		wsiModelImpl._originalUuid = wsiModelImpl._uuid;

		wsiModelImpl._originalGroupId = wsiModelImpl._groupId;

		wsiModelImpl._setOriginalGroupId = false;

		wsiModelImpl._originalCompanyId = wsiModelImpl._companyId;

		wsiModelImpl._setOriginalCompanyId = false;

		wsiModelImpl._setModifiedDate = false;

		wsiModelImpl._originalFilename = wsiModelImpl._filename;

		wsiModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<wsi> toCacheModel() {
		wsiCacheModel wsiCacheModel = new wsiCacheModel();

		wsiCacheModel.uuid = getUuid();

		String uuid = wsiCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			wsiCacheModel.uuid = null;
		}

		wsiCacheModel.wsiId = getWsiId();

		wsiCacheModel.groupId = getGroupId();

		wsiCacheModel.companyId = getCompanyId();

		wsiCacheModel.userId = getUserId();

		wsiCacheModel.userName = getUserName();

		String userName = wsiCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			wsiCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			wsiCacheModel.createDate = createDate.getTime();
		}
		else {
			wsiCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			wsiCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			wsiCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		wsiCacheModel.status = getStatus();

		wsiCacheModel.statusByUserId = getStatusByUserId();

		wsiCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = wsiCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			wsiCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			wsiCacheModel.statusDate = statusDate.getTime();
		}
		else {
			wsiCacheModel.statusDate = Long.MIN_VALUE;
		}

		wsiCacheModel.filename = getFilename();

		String filename = wsiCacheModel.filename;

		if ((filename != null) && (filename.length() == 0)) {
			wsiCacheModel.filename = null;
		}

		wsiCacheModel.hashmrxs = getHashmrxs();

		String hashmrxs = wsiCacheModel.hashmrxs;

		if ((hashmrxs != null) && (hashmrxs.length() == 0)) {
			wsiCacheModel.hashmrxs = null;
		}

		Date scanstart = getScanstart();

		if (scanstart != null) {
			wsiCacheModel.scanstart = scanstart.getTime();
		}
		else {
			wsiCacheModel.scanstart = Long.MIN_VALUE;
		}

		wsiCacheModel.scanduration = getScanduration();

		return wsiCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(33);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", wsiId=");
		sb.append(getWsiId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", statusByUserId=");
		sb.append(getStatusByUserId());
		sb.append(", statusByUserName=");
		sb.append(getStatusByUserName());
		sb.append(", statusDate=");
		sb.append(getStatusDate());
		sb.append(", filename=");
		sb.append(getFilename());
		sb.append(", hashmrxs=");
		sb.append(getHashmrxs());
		sb.append(", scanstart=");
		sb.append(getScanstart());
		sb.append(", scanduration=");
		sb.append(getScanduration());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(52);

		sb.append("<model><model-name>");
		sb.append("at.graz.meduni.bibbox.digitalpathology.model.wsi");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>wsiId</column-name><column-value><![CDATA[");
		sb.append(getWsiId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserId</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserName</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusDate</column-name><column-value><![CDATA[");
		sb.append(getStatusDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>filename</column-name><column-value><![CDATA[");
		sb.append(getFilename());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hashmrxs</column-name><column-value><![CDATA[");
		sb.append(getHashmrxs());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>scanstart</column-name><column-value><![CDATA[");
		sb.append(getScanstart());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>scanduration</column-name><column-value><![CDATA[");
		sb.append(getScanduration());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = wsi.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			wsi.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _wsiId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _filename;
	private String _originalFilename;
	private String _hashmrxs;
	private Date _scanstart;
	private long _scanduration;
	private long _columnBitmask;
	private wsi _escapedModel;
}