create table medicaldataset_ImportMedicalDataSet (
	uuid_ varchar(75) null,
	importMedicalDataSetId bigint not null primary key,
	groupId bigint,
	companyId bigint,
	userId bigint,
	userName varchar(75) null,
	createDate timestamp null,
	modifiedDate timestamp null,
	status int,
	statusByUserId bigint,
	statusByUserName varchar(75) null,
	statusDate timestamp null,
	importName varchar(75) null,
	importType varchar(75) null,
	imiJobId bigint,
	description longvarchar null,
	fileName varchar(75) null,
	filePath longvarchar null,
	fileId bigint,
	importCount int,
	importStatus int
);

create table medicaldataset_ImportMedicalDataSetFieldMap (
	uuid_ varchar(75) null,
	importMedicalDataSetFieldMapId bigint not null primary key,
	groupId bigint,
	companyId bigint,
	userId bigint,
	userName varchar(75) null,
	createDate timestamp null,
	modifiedDate timestamp null,
	status int,
	statusByUserId bigint,
	statusByUserName varchar(75) null,
	statusDate timestamp null,
	importMedicalDataSetId bigint,
	importField longvarchar null,
	importFieldPath longvarchar null,
	sampleValue longvarchar null,
	TableName longvarchar null,
	TableField longvarchar null
);

create table medicaldataset_ImportMedicalDataSetLog (
	uuid_ varchar(75) null,
	importMedicalDataSetLogId bigint not null primary key,
	groupId bigint,
	companyId bigint,
	userId bigint,
	userName varchar(75) null,
	createDate timestamp null,
	modifiedDate timestamp null,
	status int,
	statusByUserId bigint,
	statusByUserName varchar(75) null,
	statusDate timestamp null,
	importMedicalDataSetId bigint,
	importStatus int,
	importStatusLog longvarchar null
);

create table medicaldataset_KloetzelBuch (
	uuid_ varchar(75) null,
	kloetzelBuchId bigint not null primary key,
	groupId bigint,
	companyId bigint,
	userId bigint,
	userName varchar(75) null,
	createDate timestamp null,
	modifiedDate timestamp null,
	status int,
	statusByUserId bigint,
	statusByUserName varchar(75) null,
	statusDate timestamp null,
	medicalRecordId bigint,
	histonumberStart bigint,
	histonumberEnd bigint,
	histonumberRunning int,
	histonumber bigint,
	kloetzelBuchRunning int,
	oid varchar(75) null,
	bid varchar(75) null,
	area varchar(75) null,
	type_ varchar(75) null,
	acronym varchar(75) null,
	text_ longvarchar null,
	info longvarchar null,
	count int,
	numberOfPieces int,
	kbStatus int,
	sort int,
	color varchar(75) null,
	kbDate timestamp null,
	day varchar(75) null,
	pocessinguser varchar(75) null,
	organizationUnit varchar(75) null
);

create table medicaldataset_MedicalRecord (
	uuid_ varchar(75) null,
	medicalRecordId bigint not null primary key,
	groupId bigint,
	companyId bigint,
	userId bigint,
	userName varchar(75) null,
	createDate timestamp null,
	modifiedDate timestamp null,
	status int,
	statusByUserId bigint,
	statusByUserName varchar(75) null,
	statusDate timestamp null,
	importMedicalDataSetId bigint,
	histonumberStart bigint,
	histonumberEnd bigint,
	histonumberRunning int,
	iNumber bigint,
	vPatientId bigint,
	vHistonNumber bigint,
	bbPseudonym bigint,
	area varchar(75) null
);

create table medicaldataset_PathologyData (
	uuid_ varchar(75) null,
	pathologyDataId bigint not null primary key,
	groupId bigint,
	companyId bigint,
	userId bigint,
	userName varchar(75) null,
	createDate timestamp null,
	modifiedDate timestamp null,
	status int,
	statusByUserId bigint,
	statusByUserName varchar(75) null,
	statusDate timestamp null,
	medicalRecordId bigint,
	receivedDate timestamp null,
	validationDate timestamp null,
	patientAge int,
	sender varchar(1000) null,
	extractionMethode varchar(1000) null,
	reportingPhysician1 varchar(1000) null,
	reportingPhysician2 varchar(1000) null,
	gynPhysician varchar(75) null,
	validationPhysician1 varchar(1000) null,
	validationPhysician2 varchar(1000) null,
	reportStatus varchar(75) null,
	numberOfBlockes int,
	numberOfSlides int,
	basicDisease varchar(1000) null,
	causeOfDeath varchar(1000) null,
	material varchar(1000) null,
	materialExtended varchar(1000) null,
	macroscopicDescription longvarchar null,
	microscopicDescription longvarchar null,
	histologicDescription longvarchar null,
	molecularPathologicDescription longvarchar null,
	zytologieDescription longvarchar null,
	pathologicDiagnosis longvarchar null,
	frozenSectionDiagnosis longvarchar null,
	molecularPathologicDiagnosis longvarchar null,
	zytologieDiagnosis longvarchar null,
	neuroPathologicDiagnosis longvarchar null,
	comment_ longvarchar null,
	zytologiecomment longvarchar null,
	obduktionsart longvarchar null,
	grad varchar(75) null,
	tnmp varchar(75) null,
	tnmt varchar(75) null,
	tnmn varchar(75) null,
	tnmm varchar(75) null,
	tnmr varchar(75) null,
	tnml varchar(75) null,
	tnmv varchar(75) null,
	tnmpn varchar(75) null,
	dgcode1 varchar(75) null,
	dgcode2 varchar(75) null,
	pap varchar(75) null,
	smearQuality varchar(75) null
);
