create table medicaldataset_ImportMedicalDataSet (
	uuid_ varchar(75) null,
	importMedicalDataSetId bigint not null primary key,
	groupId bigint,
	companyId bigint,
	userId bigint,
	userName varchar(75) null,
	createDate datetime null,
	modifiedDate datetime null,
	status integer,
	statusByUserId bigint,
	statusByUserName varchar(75) null,
	statusDate datetime null,
	importName varchar(75) null,
	importType varchar(75) null,
	imiJobId bigint,
	description longtext null,
	fileName varchar(75) null,
	filePath longtext null,
	fileId bigint,
	importCount integer,
	importStatus integer
) engine InnoDB;

create table medicaldataset_ImportMedicalDataSetFieldMap (
	uuid_ varchar(75) null,
	importMedicalDataSetFieldMapId bigint not null primary key,
	groupId bigint,
	companyId bigint,
	userId bigint,
	userName varchar(75) null,
	createDate datetime null,
	modifiedDate datetime null,
	status integer,
	statusByUserId bigint,
	statusByUserName varchar(75) null,
	statusDate datetime null,
	importMedicalDataSetId bigint,
	importField longtext null,
	importFieldPath longtext null,
	sampleValue longtext null,
	TableName longtext null,
	TableField longtext null
) engine InnoDB;

create table medicaldataset_ImportMedicalDataSetLog (
	uuid_ varchar(75) null,
	importMedicalDataSetLogId bigint not null primary key,
	groupId bigint,
	companyId bigint,
	userId bigint,
	userName varchar(75) null,
	createDate datetime null,
	modifiedDate datetime null,
	status integer,
	statusByUserId bigint,
	statusByUserName varchar(75) null,
	statusDate datetime null,
	importMedicalDataSetId bigint,
	importStatus integer,
	importStatusLog longtext null
) engine InnoDB;

create table medicaldataset_KloetzelBuch (
	uuid_ varchar(75) null,
	kloetzelBuchId bigint not null primary key,
	groupId bigint,
	companyId bigint,
	userId bigint,
	userName varchar(75) null,
	createDate datetime null,
	modifiedDate datetime null,
	status integer,
	statusByUserId bigint,
	statusByUserName varchar(75) null,
	statusDate datetime null,
	medicalRecordId bigint,
	histonumberStart bigint,
	histonumberEnd bigint,
	histonumberRunning integer,
	histonumber bigint,
	kloetzelBuchRunning integer,
	oid varchar(75) null,
	bid varchar(75) null,
	area varchar(75) null,
	type_ varchar(75) null,
	acronym varchar(75) null,
	text_ longtext null,
	info longtext null,
	count integer,
	numberOfPieces integer,
	kbStatus integer,
	sort integer,
	color varchar(75) null,
	kbDate datetime null,
	day varchar(75) null,
	pocessinguser varchar(75) null,
	organizationUnit varchar(75) null
) engine InnoDB;

create table medicaldataset_MedicalRecord (
	uuid_ varchar(75) null,
	medicalRecordId bigint not null primary key,
	groupId bigint,
	companyId bigint,
	userId bigint,
	userName varchar(75) null,
	createDate datetime null,
	modifiedDate datetime null,
	status integer,
	statusByUserId bigint,
	statusByUserName varchar(75) null,
	statusDate datetime null,
	importMedicalDataSetId bigint,
	histonumberStart bigint,
	histonumberEnd bigint,
	histonumberRunning integer,
	iNumber bigint,
	vPatientId bigint,
	vHistonNumber bigint,
	bbPseudonym bigint,
	area varchar(75) null
) engine InnoDB;

create table medicaldataset_PathologyData (
	uuid_ varchar(75) null,
	pathologyDataId bigint not null primary key,
	groupId bigint,
	companyId bigint,
	userId bigint,
	userName varchar(75) null,
	createDate datetime null,
	modifiedDate datetime null,
	status integer,
	statusByUserId bigint,
	statusByUserName varchar(75) null,
	statusDate datetime null,
	medicalRecordId bigint,
	receivedDate datetime null,
	validationDate datetime null,
	patientAge integer,
	sender varchar(1000) null,
	extractionMethode varchar(1000) null,
	reportingPhysician1 varchar(1000) null,
	reportingPhysician2 varchar(1000) null,
	gynPhysician varchar(75) null,
	validationPhysician1 varchar(1000) null,
	validationPhysician2 varchar(1000) null,
	reportStatus varchar(75) null,
	numberOfBlockes integer,
	numberOfSlides integer,
	basicDisease varchar(1000) null,
	causeOfDeath varchar(1000) null,
	material varchar(1000) null,
	materialExtended varchar(1000) null,
	macroscopicDescription longtext null,
	microscopicDescription longtext null,
	histologicDescription longtext null,
	molecularPathologicDescription longtext null,
	zytologieDescription longtext null,
	pathologicDiagnosis longtext null,
	frozenSectionDiagnosis longtext null,
	molecularPathologicDiagnosis longtext null,
	zytologieDiagnosis longtext null,
	neuroPathologicDiagnosis longtext null,
	comment_ longtext null,
	zytologiecomment longtext null,
	obduktionsart longtext null,
	grad varchar(75) null,
	tnmp varchar(75) null,
	tnmt varchar(75) null,
	tnmn varchar(75) null,
	tnmm varchar(75) null,
	tnmr varchar(75) null,
	tnml varchar(75) null,
	tnmv varchar(75) null,
	tnmpn varchar(75) null,
	dgcode1 varchar(75) null,
	dgcode2 varchar(75) null,
	pap varchar(75) null,
	smearQuality varchar(75) null
) engine InnoDB;
