/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.bibbox.digitalpathology.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the wsihash service. Represents a row in the &quot;DP_wsihash&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.graz.meduni.bibbox.digitalpathology.model.impl.wsihashModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.graz.meduni.bibbox.digitalpathology.model.impl.wsihashImpl}.
 * </p>
 *
 * @author robert
 * @see wsihash
 * @see at.graz.meduni.bibbox.digitalpathology.model.impl.wsihashImpl
 * @see at.graz.meduni.bibbox.digitalpathology.model.impl.wsihashModelImpl
 * @generated
 */
@ProviderType
public interface wsihashModel extends BaseModel<wsihash>, GroupedModel,
	ShardedModel, StagedAuditedModel, WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a wsihash model instance should use the {@link wsihash} interface instead.
	 */

	/**
	 * Returns the primary key of this wsihash.
	 *
	 * @return the primary key of this wsihash
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this wsihash.
	 *
	 * @param primaryKey the primary key of this wsihash
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this wsihash.
	 *
	 * @return the uuid of this wsihash
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this wsihash.
	 *
	 * @param uuid the uuid of this wsihash
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the wsihash ID of this wsihash.
	 *
	 * @return the wsihash ID of this wsihash
	 */
	public long getWsihashId();

	/**
	 * Sets the wsihash ID of this wsihash.
	 *
	 * @param wsihashId the wsihash ID of this wsihash
	 */
	public void setWsihashId(long wsihashId);

	/**
	 * Returns the group ID of this wsihash.
	 *
	 * @return the group ID of this wsihash
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this wsihash.
	 *
	 * @param groupId the group ID of this wsihash
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this wsihash.
	 *
	 * @return the company ID of this wsihash
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this wsihash.
	 *
	 * @param companyId the company ID of this wsihash
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this wsihash.
	 *
	 * @return the user ID of this wsihash
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this wsihash.
	 *
	 * @param userId the user ID of this wsihash
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this wsihash.
	 *
	 * @return the user uuid of this wsihash
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this wsihash.
	 *
	 * @param userUuid the user uuid of this wsihash
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this wsihash.
	 *
	 * @return the user name of this wsihash
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this wsihash.
	 *
	 * @param userName the user name of this wsihash
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this wsihash.
	 *
	 * @return the create date of this wsihash
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this wsihash.
	 *
	 * @param createDate the create date of this wsihash
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this wsihash.
	 *
	 * @return the modified date of this wsihash
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this wsihash.
	 *
	 * @param modifiedDate the modified date of this wsihash
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this wsihash.
	 *
	 * @return the status of this wsihash
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this wsihash.
	 *
	 * @param status the status of this wsihash
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this wsihash.
	 *
	 * @return the status by user ID of this wsihash
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this wsihash.
	 *
	 * @param statusByUserId the status by user ID of this wsihash
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this wsihash.
	 *
	 * @return the status by user uuid of this wsihash
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this wsihash.
	 *
	 * @param statusByUserUuid the status by user uuid of this wsihash
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this wsihash.
	 *
	 * @return the status by user name of this wsihash
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this wsihash.
	 *
	 * @param statusByUserName the status by user name of this wsihash
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this wsihash.
	 *
	 * @return the status date of this wsihash
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this wsihash.
	 *
	 * @param statusDate the status date of this wsihash
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the wsi ID of this wsihash.
	 *
	 * @return the wsi ID of this wsihash
	 */
	public long getWsiId();

	/**
	 * Sets the wsi ID of this wsihash.
	 *
	 * @param wsiId the wsi ID of this wsihash
	 */
	public void setWsiId(long wsiId);

	/**
	 * Returns the filename of this wsihash.
	 *
	 * @return the filename of this wsihash
	 */
	@AutoEscape
	public String getFilename();

	/**
	 * Sets the filename of this wsihash.
	 *
	 * @param filename the filename of this wsihash
	 */
	public void setFilename(String filename);

	/**
	 * Returns the hash of this wsihash.
	 *
	 * @return the hash of this wsihash
	 */
	@AutoEscape
	public String getHash();

	/**
	 * Sets the hash of this wsihash.
	 *
	 * @param hash the hash of this wsihash
	 */
	public void setHash(String hash);

	/**
	 * Returns <code>true</code> if this wsihash is approved.
	 *
	 * @return <code>true</code> if this wsihash is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this wsihash is denied.
	 *
	 * @return <code>true</code> if this wsihash is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this wsihash is a draft.
	 *
	 * @return <code>true</code> if this wsihash is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this wsihash is expired.
	 *
	 * @return <code>true</code> if this wsihash is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this wsihash is inactive.
	 *
	 * @return <code>true</code> if this wsihash is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this wsihash is incomplete.
	 *
	 * @return <code>true</code> if this wsihash is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this wsihash is pending.
	 *
	 * @return <code>true</code> if this wsihash is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this wsihash is scheduled.
	 *
	 * @return <code>true</code> if this wsihash is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		at.graz.meduni.bibbox.digitalpathology.model.wsihash wsihash);

	@Override
	public int hashCode();

	@Override
	public CacheModel<at.graz.meduni.bibbox.digitalpathology.model.wsihash> toCacheModel();

	@Override
	public at.graz.meduni.bibbox.digitalpathology.model.wsihash toEscapedModel();

	@Override
	public at.graz.meduni.bibbox.digitalpathology.model.wsihash toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}