/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.bibbox.digitalpathology.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the wsi service. Represents a row in the &quot;DP_wsi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.graz.meduni.bibbox.digitalpathology.model.impl.wsiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.graz.meduni.bibbox.digitalpathology.model.impl.wsiImpl}.
 * </p>
 *
 * @author robert
 * @see wsi
 * @see at.graz.meduni.bibbox.digitalpathology.model.impl.wsiImpl
 * @see at.graz.meduni.bibbox.digitalpathology.model.impl.wsiModelImpl
 * @generated
 */
@ProviderType
public interface wsiModel extends BaseModel<wsi>, GroupedModel, ShardedModel,
	StagedAuditedModel, WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a wsi model instance should use the {@link wsi} interface instead.
	 */

	/**
	 * Returns the primary key of this wsi.
	 *
	 * @return the primary key of this wsi
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this wsi.
	 *
	 * @param primaryKey the primary key of this wsi
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this wsi.
	 *
	 * @return the uuid of this wsi
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this wsi.
	 *
	 * @param uuid the uuid of this wsi
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the wsi ID of this wsi.
	 *
	 * @return the wsi ID of this wsi
	 */
	public long getWsiId();

	/**
	 * Sets the wsi ID of this wsi.
	 *
	 * @param wsiId the wsi ID of this wsi
	 */
	public void setWsiId(long wsiId);

	/**
	 * Returns the group ID of this wsi.
	 *
	 * @return the group ID of this wsi
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this wsi.
	 *
	 * @param groupId the group ID of this wsi
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this wsi.
	 *
	 * @return the company ID of this wsi
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this wsi.
	 *
	 * @param companyId the company ID of this wsi
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this wsi.
	 *
	 * @return the user ID of this wsi
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this wsi.
	 *
	 * @param userId the user ID of this wsi
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this wsi.
	 *
	 * @return the user uuid of this wsi
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this wsi.
	 *
	 * @param userUuid the user uuid of this wsi
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this wsi.
	 *
	 * @return the user name of this wsi
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this wsi.
	 *
	 * @param userName the user name of this wsi
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this wsi.
	 *
	 * @return the create date of this wsi
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this wsi.
	 *
	 * @param createDate the create date of this wsi
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this wsi.
	 *
	 * @return the modified date of this wsi
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this wsi.
	 *
	 * @param modifiedDate the modified date of this wsi
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this wsi.
	 *
	 * @return the status of this wsi
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this wsi.
	 *
	 * @param status the status of this wsi
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this wsi.
	 *
	 * @return the status by user ID of this wsi
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this wsi.
	 *
	 * @param statusByUserId the status by user ID of this wsi
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this wsi.
	 *
	 * @return the status by user uuid of this wsi
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this wsi.
	 *
	 * @param statusByUserUuid the status by user uuid of this wsi
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this wsi.
	 *
	 * @return the status by user name of this wsi
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this wsi.
	 *
	 * @param statusByUserName the status by user name of this wsi
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this wsi.
	 *
	 * @return the status date of this wsi
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this wsi.
	 *
	 * @param statusDate the status date of this wsi
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the filename of this wsi.
	 *
	 * @return the filename of this wsi
	 */
	@AutoEscape
	public String getFilename();

	/**
	 * Sets the filename of this wsi.
	 *
	 * @param filename the filename of this wsi
	 */
	public void setFilename(String filename);

	/**
	 * Returns the hashmrxs of this wsi.
	 *
	 * @return the hashmrxs of this wsi
	 */
	@AutoEscape
	public String getHashmrxs();

	/**
	 * Sets the hashmrxs of this wsi.
	 *
	 * @param hashmrxs the hashmrxs of this wsi
	 */
	public void setHashmrxs(String hashmrxs);

	/**
	 * Returns the scanstart of this wsi.
	 *
	 * @return the scanstart of this wsi
	 */
	public Date getScanstart();

	/**
	 * Sets the scanstart of this wsi.
	 *
	 * @param scanstart the scanstart of this wsi
	 */
	public void setScanstart(Date scanstart);

	/**
	 * Returns the scanduration of this wsi.
	 *
	 * @return the scanduration of this wsi
	 */
	public long getScanduration();

	/**
	 * Sets the scanduration of this wsi.
	 *
	 * @param scanduration the scanduration of this wsi
	 */
	public void setScanduration(long scanduration);

	/**
	 * Returns <code>true</code> if this wsi is approved.
	 *
	 * @return <code>true</code> if this wsi is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this wsi is denied.
	 *
	 * @return <code>true</code> if this wsi is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this wsi is a draft.
	 *
	 * @return <code>true</code> if this wsi is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this wsi is expired.
	 *
	 * @return <code>true</code> if this wsi is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this wsi is inactive.
	 *
	 * @return <code>true</code> if this wsi is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this wsi is incomplete.
	 *
	 * @return <code>true</code> if this wsi is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this wsi is pending.
	 *
	 * @return <code>true</code> if this wsi is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this wsi is scheduled.
	 *
	 * @return <code>true</code> if this wsi is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(at.graz.meduni.bibbox.digitalpathology.model.wsi wsi);

	@Override
	public int hashCode();

	@Override
	public CacheModel<at.graz.meduni.bibbox.digitalpathology.model.wsi> toCacheModel();

	@Override
	public at.graz.meduni.bibbox.digitalpathology.model.wsi toEscapedModel();

	@Override
	public at.graz.meduni.bibbox.digitalpathology.model.wsi toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}