/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.bibbox.medicaldataset.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ImportMedicalDataSet service. Represents a row in the &quot;FOO_ImportMedicalDataSet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.graz.meduni.bibbox.medicaldataset.model.impl.ImportMedicalDataSetModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.graz.meduni.bibbox.medicaldataset.model.impl.ImportMedicalDataSetImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ImportMedicalDataSet
 * @see at.graz.meduni.bibbox.medicaldataset.model.impl.ImportMedicalDataSetImpl
 * @see at.graz.meduni.bibbox.medicaldataset.model.impl.ImportMedicalDataSetModelImpl
 * @generated
 */
@ProviderType
public interface ImportMedicalDataSetModel extends BaseModel<ImportMedicalDataSet>,
	GroupedModel, ShardedModel, StagedAuditedModel, WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a import medical data set model instance should use the {@link ImportMedicalDataSet} interface instead.
	 */

	/**
	 * Returns the primary key of this import medical data set.
	 *
	 * @return the primary key of this import medical data set
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this import medical data set.
	 *
	 * @param primaryKey the primary key of this import medical data set
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this import medical data set.
	 *
	 * @return the uuid of this import medical data set
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this import medical data set.
	 *
	 * @param uuid the uuid of this import medical data set
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the import medical data set ID of this import medical data set.
	 *
	 * @return the import medical data set ID of this import medical data set
	 */
	public long getImportMedicalDataSetId();

	/**
	 * Sets the import medical data set ID of this import medical data set.
	 *
	 * @param importMedicalDataSetId the import medical data set ID of this import medical data set
	 */
	public void setImportMedicalDataSetId(long importMedicalDataSetId);

	/**
	 * Returns the group ID of this import medical data set.
	 *
	 * @return the group ID of this import medical data set
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this import medical data set.
	 *
	 * @param groupId the group ID of this import medical data set
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this import medical data set.
	 *
	 * @return the company ID of this import medical data set
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this import medical data set.
	 *
	 * @param companyId the company ID of this import medical data set
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this import medical data set.
	 *
	 * @return the user ID of this import medical data set
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this import medical data set.
	 *
	 * @param userId the user ID of this import medical data set
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this import medical data set.
	 *
	 * @return the user uuid of this import medical data set
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this import medical data set.
	 *
	 * @param userUuid the user uuid of this import medical data set
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this import medical data set.
	 *
	 * @return the user name of this import medical data set
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this import medical data set.
	 *
	 * @param userName the user name of this import medical data set
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this import medical data set.
	 *
	 * @return the create date of this import medical data set
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this import medical data set.
	 *
	 * @param createDate the create date of this import medical data set
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this import medical data set.
	 *
	 * @return the modified date of this import medical data set
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this import medical data set.
	 *
	 * @param modifiedDate the modified date of this import medical data set
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this import medical data set.
	 *
	 * @return the status of this import medical data set
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this import medical data set.
	 *
	 * @param status the status of this import medical data set
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this import medical data set.
	 *
	 * @return the status by user ID of this import medical data set
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this import medical data set.
	 *
	 * @param statusByUserId the status by user ID of this import medical data set
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this import medical data set.
	 *
	 * @return the status by user uuid of this import medical data set
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this import medical data set.
	 *
	 * @param statusByUserUuid the status by user uuid of this import medical data set
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this import medical data set.
	 *
	 * @return the status by user name of this import medical data set
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this import medical data set.
	 *
	 * @param statusByUserName the status by user name of this import medical data set
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this import medical data set.
	 *
	 * @return the status date of this import medical data set
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this import medical data set.
	 *
	 * @param statusDate the status date of this import medical data set
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the import name of this import medical data set.
	 *
	 * @return the import name of this import medical data set
	 */
	@AutoEscape
	public String getImportName();

	/**
	 * Sets the import name of this import medical data set.
	 *
	 * @param importName the import name of this import medical data set
	 */
	public void setImportName(String importName);

	/**
	 * Returns the import type of this import medical data set.
	 *
	 * @return the import type of this import medical data set
	 */
	@AutoEscape
	public String getImportType();

	/**
	 * Sets the import type of this import medical data set.
	 *
	 * @param importType the import type of this import medical data set
	 */
	public void setImportType(String importType);

	/**
	 * Returns the imi job ID of this import medical data set.
	 *
	 * @return the imi job ID of this import medical data set
	 */
	public long getImiJobId();

	/**
	 * Sets the imi job ID of this import medical data set.
	 *
	 * @param imiJobId the imi job ID of this import medical data set
	 */
	public void setImiJobId(long imiJobId);

	/**
	 * Returns the description of this import medical data set.
	 *
	 * @return the description of this import medical data set
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this import medical data set.
	 *
	 * @param description the description of this import medical data set
	 */
	public void setDescription(String description);

	/**
	 * Returns the file name of this import medical data set.
	 *
	 * @return the file name of this import medical data set
	 */
	@AutoEscape
	public String getFileName();

	/**
	 * Sets the file name of this import medical data set.
	 *
	 * @param fileName the file name of this import medical data set
	 */
	public void setFileName(String fileName);

	/**
	 * Returns the file path of this import medical data set.
	 *
	 * @return the file path of this import medical data set
	 */
	@AutoEscape
	public String getFilePath();

	/**
	 * Sets the file path of this import medical data set.
	 *
	 * @param filePath the file path of this import medical data set
	 */
	public void setFilePath(String filePath);

	/**
	 * Returns the file ID of this import medical data set.
	 *
	 * @return the file ID of this import medical data set
	 */
	public long getFileId();

	/**
	 * Sets the file ID of this import medical data set.
	 *
	 * @param fileId the file ID of this import medical data set
	 */
	public void setFileId(long fileId);

	/**
	 * Returns the import status of this import medical data set.
	 *
	 * @return the import status of this import medical data set
	 */
	public int getImportStatus();

	/**
	 * Sets the import status of this import medical data set.
	 *
	 * @param importStatus the import status of this import medical data set
	 */
	public void setImportStatus(int importStatus);

	/**
	 * Returns <code>true</code> if this import medical data set is approved.
	 *
	 * @return <code>true</code> if this import medical data set is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this import medical data set is denied.
	 *
	 * @return <code>true</code> if this import medical data set is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this import medical data set is a draft.
	 *
	 * @return <code>true</code> if this import medical data set is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this import medical data set is expired.
	 *
	 * @return <code>true</code> if this import medical data set is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this import medical data set is inactive.
	 *
	 * @return <code>true</code> if this import medical data set is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this import medical data set is incomplete.
	 *
	 * @return <code>true</code> if this import medical data set is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this import medical data set is pending.
	 *
	 * @return <code>true</code> if this import medical data set is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this import medical data set is scheduled.
	 *
	 * @return <code>true</code> if this import medical data set is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		at.graz.meduni.bibbox.medicaldataset.model.ImportMedicalDataSet importMedicalDataSet);

	@Override
	public int hashCode();

	@Override
	public CacheModel<at.graz.meduni.bibbox.medicaldataset.model.ImportMedicalDataSet> toCacheModel();

	@Override
	public at.graz.meduni.bibbox.medicaldataset.model.ImportMedicalDataSet toEscapedModel();

	@Override
	public at.graz.meduni.bibbox.medicaldataset.model.ImportMedicalDataSet toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}