/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.bibbox.medicaldataset.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ImportMedicalDataSetLog service. Represents a row in the &quot;medicaldataset_ImportMedicalDataSetLog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.graz.meduni.bibbox.medicaldataset.model.impl.ImportMedicalDataSetLogModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.graz.meduni.bibbox.medicaldataset.model.impl.ImportMedicalDataSetLogImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ImportMedicalDataSetLog
 * @see at.graz.meduni.bibbox.medicaldataset.model.impl.ImportMedicalDataSetLogImpl
 * @see at.graz.meduni.bibbox.medicaldataset.model.impl.ImportMedicalDataSetLogModelImpl
 * @generated
 */
@ProviderType
public interface ImportMedicalDataSetLogModel extends BaseModel<ImportMedicalDataSetLog>,
	GroupedModel, ShardedModel, StagedAuditedModel, WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a import medical data set log model instance should use the {@link ImportMedicalDataSetLog} interface instead.
	 */

	/**
	 * Returns the primary key of this import medical data set log.
	 *
	 * @return the primary key of this import medical data set log
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this import medical data set log.
	 *
	 * @param primaryKey the primary key of this import medical data set log
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this import medical data set log.
	 *
	 * @return the uuid of this import medical data set log
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this import medical data set log.
	 *
	 * @param uuid the uuid of this import medical data set log
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the import medical data set log ID of this import medical data set log.
	 *
	 * @return the import medical data set log ID of this import medical data set log
	 */
	public long getImportMedicalDataSetLogId();

	/**
	 * Sets the import medical data set log ID of this import medical data set log.
	 *
	 * @param importMedicalDataSetLogId the import medical data set log ID of this import medical data set log
	 */
	public void setImportMedicalDataSetLogId(long importMedicalDataSetLogId);

	/**
	 * Returns the group ID of this import medical data set log.
	 *
	 * @return the group ID of this import medical data set log
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this import medical data set log.
	 *
	 * @param groupId the group ID of this import medical data set log
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this import medical data set log.
	 *
	 * @return the company ID of this import medical data set log
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this import medical data set log.
	 *
	 * @param companyId the company ID of this import medical data set log
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this import medical data set log.
	 *
	 * @return the user ID of this import medical data set log
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this import medical data set log.
	 *
	 * @param userId the user ID of this import medical data set log
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this import medical data set log.
	 *
	 * @return the user uuid of this import medical data set log
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this import medical data set log.
	 *
	 * @param userUuid the user uuid of this import medical data set log
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this import medical data set log.
	 *
	 * @return the user name of this import medical data set log
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this import medical data set log.
	 *
	 * @param userName the user name of this import medical data set log
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this import medical data set log.
	 *
	 * @return the create date of this import medical data set log
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this import medical data set log.
	 *
	 * @param createDate the create date of this import medical data set log
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this import medical data set log.
	 *
	 * @return the modified date of this import medical data set log
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this import medical data set log.
	 *
	 * @param modifiedDate the modified date of this import medical data set log
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this import medical data set log.
	 *
	 * @return the status of this import medical data set log
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this import medical data set log.
	 *
	 * @param status the status of this import medical data set log
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this import medical data set log.
	 *
	 * @return the status by user ID of this import medical data set log
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this import medical data set log.
	 *
	 * @param statusByUserId the status by user ID of this import medical data set log
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this import medical data set log.
	 *
	 * @return the status by user uuid of this import medical data set log
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this import medical data set log.
	 *
	 * @param statusByUserUuid the status by user uuid of this import medical data set log
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this import medical data set log.
	 *
	 * @return the status by user name of this import medical data set log
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this import medical data set log.
	 *
	 * @param statusByUserName the status by user name of this import medical data set log
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this import medical data set log.
	 *
	 * @return the status date of this import medical data set log
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this import medical data set log.
	 *
	 * @param statusDate the status date of this import medical data set log
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the import medical data set ID of this import medical data set log.
	 *
	 * @return the import medical data set ID of this import medical data set log
	 */
	public long getImportMedicalDataSetId();

	/**
	 * Sets the import medical data set ID of this import medical data set log.
	 *
	 * @param importMedicalDataSetId the import medical data set ID of this import medical data set log
	 */
	public void setImportMedicalDataSetId(long importMedicalDataSetId);

	/**
	 * Returns the import status of this import medical data set log.
	 *
	 * @return the import status of this import medical data set log
	 */
	public int getImportStatus();

	/**
	 * Sets the import status of this import medical data set log.
	 *
	 * @param importStatus the import status of this import medical data set log
	 */
	public void setImportStatus(int importStatus);

	/**
	 * Returns the import status log of this import medical data set log.
	 *
	 * @return the import status log of this import medical data set log
	 */
	@AutoEscape
	public String getImportStatusLog();

	/**
	 * Sets the import status log of this import medical data set log.
	 *
	 * @param importStatusLog the import status log of this import medical data set log
	 */
	public void setImportStatusLog(String importStatusLog);

	/**
	 * Returns <code>true</code> if this import medical data set log is approved.
	 *
	 * @return <code>true</code> if this import medical data set log is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this import medical data set log is denied.
	 *
	 * @return <code>true</code> if this import medical data set log is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this import medical data set log is a draft.
	 *
	 * @return <code>true</code> if this import medical data set log is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this import medical data set log is expired.
	 *
	 * @return <code>true</code> if this import medical data set log is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this import medical data set log is inactive.
	 *
	 * @return <code>true</code> if this import medical data set log is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this import medical data set log is incomplete.
	 *
	 * @return <code>true</code> if this import medical data set log is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this import medical data set log is pending.
	 *
	 * @return <code>true</code> if this import medical data set log is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this import medical data set log is scheduled.
	 *
	 * @return <code>true</code> if this import medical data set log is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		at.graz.meduni.bibbox.medicaldataset.model.ImportMedicalDataSetLog importMedicalDataSetLog);

	@Override
	public int hashCode();

	@Override
	public CacheModel<at.graz.meduni.bibbox.medicaldataset.model.ImportMedicalDataSetLog> toCacheModel();

	@Override
	public at.graz.meduni.bibbox.medicaldataset.model.ImportMedicalDataSetLog toEscapedModel();

	@Override
	public at.graz.meduni.bibbox.medicaldataset.model.ImportMedicalDataSetLog toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}