/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.graz.meduni.bibbox.medicaldataset.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ImportMedicalDataSetFieldMap service. Represents a row in the &quot;FOO_ImportMedicalDataSetFieldMap&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link at.graz.meduni.bibbox.medicaldataset.model.impl.ImportMedicalDataSetFieldMapModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link at.graz.meduni.bibbox.medicaldataset.model.impl.ImportMedicalDataSetFieldMapImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ImportMedicalDataSetFieldMap
 * @see at.graz.meduni.bibbox.medicaldataset.model.impl.ImportMedicalDataSetFieldMapImpl
 * @see at.graz.meduni.bibbox.medicaldataset.model.impl.ImportMedicalDataSetFieldMapModelImpl
 * @generated
 */
@ProviderType
public interface ImportMedicalDataSetFieldMapModel extends BaseModel<ImportMedicalDataSetFieldMap>,
	GroupedModel, ShardedModel, StagedAuditedModel, WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a import medical data set field map model instance should use the {@link ImportMedicalDataSetFieldMap} interface instead.
	 */

	/**
	 * Returns the primary key of this import medical data set field map.
	 *
	 * @return the primary key of this import medical data set field map
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this import medical data set field map.
	 *
	 * @param primaryKey the primary key of this import medical data set field map
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this import medical data set field map.
	 *
	 * @return the uuid of this import medical data set field map
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this import medical data set field map.
	 *
	 * @param uuid the uuid of this import medical data set field map
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the import medical data set field map ID of this import medical data set field map.
	 *
	 * @return the import medical data set field map ID of this import medical data set field map
	 */
	public long getImportMedicalDataSetFieldMapId();

	/**
	 * Sets the import medical data set field map ID of this import medical data set field map.
	 *
	 * @param importMedicalDataSetFieldMapId the import medical data set field map ID of this import medical data set field map
	 */
	public void setImportMedicalDataSetFieldMapId(
		long importMedicalDataSetFieldMapId);

	/**
	 * Returns the group ID of this import medical data set field map.
	 *
	 * @return the group ID of this import medical data set field map
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this import medical data set field map.
	 *
	 * @param groupId the group ID of this import medical data set field map
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this import medical data set field map.
	 *
	 * @return the company ID of this import medical data set field map
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this import medical data set field map.
	 *
	 * @param companyId the company ID of this import medical data set field map
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this import medical data set field map.
	 *
	 * @return the user ID of this import medical data set field map
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this import medical data set field map.
	 *
	 * @param userId the user ID of this import medical data set field map
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this import medical data set field map.
	 *
	 * @return the user uuid of this import medical data set field map
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this import medical data set field map.
	 *
	 * @param userUuid the user uuid of this import medical data set field map
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this import medical data set field map.
	 *
	 * @return the user name of this import medical data set field map
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this import medical data set field map.
	 *
	 * @param userName the user name of this import medical data set field map
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this import medical data set field map.
	 *
	 * @return the create date of this import medical data set field map
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this import medical data set field map.
	 *
	 * @param createDate the create date of this import medical data set field map
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this import medical data set field map.
	 *
	 * @return the modified date of this import medical data set field map
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this import medical data set field map.
	 *
	 * @param modifiedDate the modified date of this import medical data set field map
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this import medical data set field map.
	 *
	 * @return the status of this import medical data set field map
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this import medical data set field map.
	 *
	 * @param status the status of this import medical data set field map
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this import medical data set field map.
	 *
	 * @return the status by user ID of this import medical data set field map
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this import medical data set field map.
	 *
	 * @param statusByUserId the status by user ID of this import medical data set field map
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this import medical data set field map.
	 *
	 * @return the status by user uuid of this import medical data set field map
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this import medical data set field map.
	 *
	 * @param statusByUserUuid the status by user uuid of this import medical data set field map
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this import medical data set field map.
	 *
	 * @return the status by user name of this import medical data set field map
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this import medical data set field map.
	 *
	 * @param statusByUserName the status by user name of this import medical data set field map
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this import medical data set field map.
	 *
	 * @return the status date of this import medical data set field map
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this import medical data set field map.
	 *
	 * @param statusDate the status date of this import medical data set field map
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the import medical data set ID of this import medical data set field map.
	 *
	 * @return the import medical data set ID of this import medical data set field map
	 */
	public long getImportMedicalDataSetId();

	/**
	 * Sets the import medical data set ID of this import medical data set field map.
	 *
	 * @param importMedicalDataSetId the import medical data set ID of this import medical data set field map
	 */
	public void setImportMedicalDataSetId(long importMedicalDataSetId);

	/**
	 * Returns the import field of this import medical data set field map.
	 *
	 * @return the import field of this import medical data set field map
	 */
	@AutoEscape
	public String getImportField();

	/**
	 * Sets the import field of this import medical data set field map.
	 *
	 * @param importField the import field of this import medical data set field map
	 */
	public void setImportField(String importField);

	/**
	 * Returns the import field path of this import medical data set field map.
	 *
	 * @return the import field path of this import medical data set field map
	 */
	@AutoEscape
	public String getImportFieldPath();

	/**
	 * Sets the import field path of this import medical data set field map.
	 *
	 * @param importFieldPath the import field path of this import medical data set field map
	 */
	public void setImportFieldPath(String importFieldPath);

	/**
	 * Returns the table name of this import medical data set field map.
	 *
	 * @return the table name of this import medical data set field map
	 */
	@AutoEscape
	public String getTableName();

	/**
	 * Sets the table name of this import medical data set field map.
	 *
	 * @param TableName the table name of this import medical data set field map
	 */
	public void setTableName(String TableName);

	/**
	 * Returns the table field of this import medical data set field map.
	 *
	 * @return the table field of this import medical data set field map
	 */
	@AutoEscape
	public String getTableField();

	/**
	 * Sets the table field of this import medical data set field map.
	 *
	 * @param TableField the table field of this import medical data set field map
	 */
	public void setTableField(String TableField);

	/**
	 * Returns <code>true</code> if this import medical data set field map is approved.
	 *
	 * @return <code>true</code> if this import medical data set field map is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this import medical data set field map is denied.
	 *
	 * @return <code>true</code> if this import medical data set field map is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this import medical data set field map is a draft.
	 *
	 * @return <code>true</code> if this import medical data set field map is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this import medical data set field map is expired.
	 *
	 * @return <code>true</code> if this import medical data set field map is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this import medical data set field map is inactive.
	 *
	 * @return <code>true</code> if this import medical data set field map is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this import medical data set field map is incomplete.
	 *
	 * @return <code>true</code> if this import medical data set field map is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this import medical data set field map is pending.
	 *
	 * @return <code>true</code> if this import medical data set field map is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this import medical data set field map is scheduled.
	 *
	 * @return <code>true</code> if this import medical data set field map is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		at.graz.meduni.bibbox.medicaldataset.model.ImportMedicalDataSetFieldMap importMedicalDataSetFieldMap);

	@Override
	public int hashCode();

	@Override
	public CacheModel<at.graz.meduni.bibbox.medicaldataset.model.ImportMedicalDataSetFieldMap> toCacheModel();

	@Override
	public at.graz.meduni.bibbox.medicaldataset.model.ImportMedicalDataSetFieldMap toEscapedModel();

	@Override
	public at.graz.meduni.bibbox.medicaldataset.model.ImportMedicalDataSetFieldMap toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}